// ReSharper disable All

using Lumina.Text;
using Lumina.Data;
using Lumina.Data.Structs.Excel;

namespace Lumina.Excel.GeneratedSheets
{
    [Sheet( "Frontline04", columnHash: 0x718aefbb )]
    public partial class Frontline04 : ExcelRow
    {
        
        public LazyRow< Level > Level1 { get; set; }
        public LazyRow< Level > Level2 { get; set; }
        public LazyRow< Level > Level3 { get; set; }
        public int Unknown3 { get; set; }
        public int Unknown4 { get; set; }
        public int Unknown5 { get; set; }
        public int Unknown6 { get; set; }
        public int Unknown7 { get; set; }
        public int Unknown8 { get; set; }
        public int Unknown9 { get; set; }
        public int Unknown10 { get; set; }
        public int Unknown11 { get; set; }
        public int Unknown12 { get; set; }
        public int Unknown13 { get; set; }
        public int Unknown14 { get; set; }
        public int Unknown15 { get; set; }
        public int Unknown16 { get; set; }
        public int Unknown17 { get; set; }
        public int Unknown18 { get; set; }
        public int Unknown19 { get; set; }
        public int Unknown20 { get; set; }
        public int Unknown21 { get; set; }
        public int Unknown22 { get; set; }
        public int Unknown23 { get; set; }
        public int Unknown24 { get; set; }
        public int Unknown25 { get; set; }
        public int Unknown26 { get; set; }
        public int Unknown27 { get; set; }
        public int Unknown28 { get; set; }
        public int Unknown29 { get; set; }
        public int Unknown30 { get; set; }
        public int Unknown31 { get; set; }
        public int Unknown32 { get; set; }
        public int Unknown33 { get; set; }
        public int Unknown34 { get; set; }
        public int Unknown35 { get; set; }
        public int Unknown36 { get; set; }
        public int Unknown37 { get; set; }
        public int Unknown38 { get; set; }
        public int Unknown39 { get; set; }
        public int Unknown40 { get; set; }
        public int Unknown41 { get; set; }
        public int Unknown42 { get; set; }
        public int Unknown43 { get; set; }
        public int Unknown44 { get; set; }
        public int Unknown45 { get; set; }
        public int Unknown46 { get; set; }
        public int Unknown47 { get; set; }
        public int Unknown48 { get; set; }
        public int Unknown49 { get; set; }
        public int Unknown50 { get; set; }
        public int Unknown51 { get; set; }
        public int Unknown52 { get; set; }
        public int Unknown53 { get; set; }
        public int Unknown54 { get; set; }
        public int Unknown55 { get; set; }
        public int Unknown56 { get; set; }
        public byte Unknown57 { get; set; }
        public byte Unknown58 { get; set; }
        public byte Unknown59 { get; set; }
        public byte Unknown60 { get; set; }
        public byte Unknown61 { get; set; }
        public byte Unknown62 { get; set; }
        public byte Unknown63 { get; set; }
        public byte Unknown64 { get; set; }
        public byte Unknown65 { get; set; }
        public byte Unknown66 { get; set; }
        public byte Unknown67 { get; set; }
        public byte Unknown68 { get; set; }
        public byte Unknown69 { get; set; }
        public byte Unknown70 { get; set; }
        public byte Unknown71 { get; set; }
        public byte Unknown72 { get; set; }
        public byte Unknown73 { get; set; }
        public byte Unknown74 { get; set; }
        public byte Unknown75 { get; set; }
        public byte Unknown76 { get; set; }
        public byte Unknown77 { get; set; }
        public byte Unknown78 { get; set; }
        public byte Unknown79 { get; set; }
        public byte Unknown80 { get; set; }
        public byte Unknown81 { get; set; }
        public byte Unknown82 { get; set; }
        public byte Unknown83 { get; set; }
        public byte Unknown84 { get; set; }
        public byte Unknown85 { get; set; }
        public byte Unknown86 { get; set; }
        public byte Unknown87 { get; set; }
        public byte Unknown88 { get; set; }
        public byte Unknown89 { get; set; }
        public byte Unknown90 { get; set; }
        public byte Unknown91 { get; set; }
        public byte Unknown92 { get; set; }
        public byte Unknown93 { get; set; }
        public byte Unknown94 { get; set; }
        public byte Unknown95 { get; set; }
        public byte Unknown96 { get; set; }
        public byte Unknown97 { get; set; }
        public byte Unknown98 { get; set; }
        public byte Unknown99 { get; set; }
        public byte Unknown100 { get; set; }
        public byte Unknown101 { get; set; }
        public byte Unknown102 { get; set; }
        public byte Unknown103 { get; set; }
        public byte Unknown104 { get; set; }
        public byte Unknown105 { get; set; }
        public byte Unknown106 { get; set; }
        public byte Unknown107 { get; set; }
        public byte Unknown108 { get; set; }
        public byte Unknown109 { get; set; }
        public byte Unknown110 { get; set; }
        public byte Unknown111 { get; set; }
        public byte Unknown112 { get; set; }
        public byte Unknown113 { get; set; }
        public byte Unknown114 { get; set; }
        public byte Unknown115 { get; set; }
        public byte Unknown116 { get; set; }
        public byte Unknown117 { get; set; }
        public byte Unknown118 { get; set; }
        public byte Unknown119 { get; set; }
        public byte Unknown120 { get; set; }
        public byte Unknown121 { get; set; }
        public byte Unknown122 { get; set; }
        public byte Unknown123 { get; set; }
        public byte Unknown124 { get; set; }
        public byte Unknown125 { get; set; }
        public byte Unknown126 { get; set; }
        public byte Unknown127 { get; set; }
        public byte Unknown128 { get; set; }
        public byte Unknown129 { get; set; }
        public byte Unknown130 { get; set; }
        public byte Unknown131 { get; set; }
        public byte Unknown132 { get; set; }
        public byte Unknown133 { get; set; }
        public byte Unknown134 { get; set; }
        public byte Unknown135 { get; set; }
        public byte Unknown136 { get; set; }
        public byte Unknown137 { get; set; }
        public byte Unknown138 { get; set; }
        public byte Unknown139 { get; set; }
        public byte Unknown140 { get; set; }
        public byte Unknown141 { get; set; }
        public byte Unknown142 { get; set; }
        public byte Unknown143 { get; set; }
        public byte Unknown144 { get; set; }
        public byte Unknown145 { get; set; }
        public byte Unknown146 { get; set; }
        public byte Unknown147 { get; set; }
        public byte Unknown148 { get; set; }
        public byte Unknown149 { get; set; }
        public byte Unknown150 { get; set; }
        public byte Unknown151 { get; set; }
        public byte Unknown152 { get; set; }
        public byte Unknown153 { get; set; }
        public byte Unknown154 { get; set; }
        public byte Unknown155 { get; set; }
        public byte Unknown156 { get; set; }
        public byte Unknown157 { get; set; }
        public byte Unknown158 { get; set; }
        public byte Unknown159 { get; set; }
        public byte Unknown160 { get; set; }
        public byte Unknown161 { get; set; }
        public byte Unknown162 { get; set; }
        public byte Unknown163 { get; set; }
        public byte Unknown164 { get; set; }
        public byte Unknown165 { get; set; }
        public byte Unknown166 { get; set; }
        public byte Unknown167 { get; set; }
        public byte Unknown168 { get; set; }
        public byte Unknown169 { get; set; }
        public byte Unknown170 { get; set; }
        public byte Unknown171 { get; set; }
        public byte Unknown172 { get; set; }
        public byte Unknown173 { get; set; }
        public byte Unknown174 { get; set; }
        public byte Unknown175 { get; set; }
        public byte Unknown176 { get; set; }
        public int Unknown177 { get; set; }
        public int Unknown178 { get; set; }
        public int Unknown179 { get; set; }
        public int Unknown180 { get; set; }
        public int Unknown181 { get; set; }
        public int Unknown182 { get; set; }
        public int Unknown183 { get; set; }
        public int Unknown184 { get; set; }
        public int Unknown185 { get; set; }
        public int Unknown186 { get; set; }
        public int Unknown187 { get; set; }
        public int Unknown188 { get; set; }
        public int Unknown189 { get; set; }
        public int Unknown190 { get; set; }
        public int Unknown191 { get; set; }
        public int Unknown192 { get; set; }
        public int Unknown193 { get; set; }
        public int Unknown194 { get; set; }
        public int Unknown195 { get; set; }
        public int Unknown196 { get; set; }
        public int Unknown197 { get; set; }
        public int Unknown198 { get; set; }
        public int Unknown199 { get; set; }
        public int Unknown200 { get; set; }
        public int Unknown201 { get; set; }
        public int Unknown202 { get; set; }
        public int Unknown203 { get; set; }
        public int Unknown204 { get; set; }
        public int Unknown205 { get; set; }
        public int Unknown206 { get; set; }
        public int Unknown207 { get; set; }
        public int Unknown208 { get; set; }
        public int Unknown209 { get; set; }
        public int Unknown210 { get; set; }
        public int Unknown211 { get; set; }
        public int Unknown212 { get; set; }
        public int Unknown213 { get; set; }
        public int Unknown214 { get; set; }
        public int Unknown215 { get; set; }
        public int Unknown216 { get; set; }
        public int Unknown217 { get; set; }
        public int Unknown218 { get; set; }
        public int Unknown219 { get; set; }
        public int Unknown220 { get; set; }
        public int Unknown221 { get; set; }
        public int Unknown222 { get; set; }
        public int Unknown223 { get; set; }
        public int Unknown224 { get; set; }
        public int Unknown225 { get; set; }
        public int Unknown226 { get; set; }
        public int Unknown227 { get; set; }
        public int Unknown228 { get; set; }
        public int Unknown229 { get; set; }
        public int Unknown230 { get; set; }
        public int Unknown231 { get; set; }
        public int Unknown232 { get; set; }
        public int Unknown233 { get; set; }
        public int Unknown234 { get; set; }
        public int Unknown235 { get; set; }
        public int Unknown236 { get; set; }
        public int Unknown237 { get; set; }
        public int Unknown238 { get; set; }
        public int Unknown239 { get; set; }
        public int Unknown240 { get; set; }
        public int Unknown241 { get; set; }
        public int Unknown242 { get; set; }
        public int Unknown243 { get; set; }
        public int Unknown244 { get; set; }
        public int Unknown245 { get; set; }
        public int Unknown246 { get; set; }
        public int Unknown247 { get; set; }
        public int Unknown248 { get; set; }
        public int Unknown249 { get; set; }
        public int Unknown250 { get; set; }
        public int Unknown251 { get; set; }
        public int Unknown252 { get; set; }
        public int Unknown253 { get; set; }
        public int Unknown254 { get; set; }
        public int Unknown255 { get; set; }
        public int Unknown256 { get; set; }
        public int Unknown257 { get; set; }
        public int Unknown258 { get; set; }
        public int Unknown259 { get; set; }
        public int Unknown260 { get; set; }
        public int Unknown261 { get; set; }
        public int Unknown262 { get; set; }
        public int Unknown263 { get; set; }
        public int Unknown264 { get; set; }
        public int Unknown265 { get; set; }
        public int Unknown266 { get; set; }
        public int Unknown267 { get; set; }
        public int Unknown268 { get; set; }
        public int Unknown269 { get; set; }
        public int Unknown270 { get; set; }
        public int Unknown271 { get; set; }
        public int Unknown272 { get; set; }
        
        public override void PopulateData( RowParser parser, GameData gameData, Language language )
        {
            base.PopulateData( parser, gameData, language );

            Level1 = new LazyRow< Level >( gameData, parser.ReadColumn< int >( 0 ), language );
            Level2 = new LazyRow< Level >( gameData, parser.ReadColumn< int >( 1 ), language );
            Level3 = new LazyRow< Level >( gameData, parser.ReadColumn< int >( 2 ), language );
            Unknown3 = parser.ReadColumn< int >( 3 );
            Unknown4 = parser.ReadColumn< int >( 4 );
            Unknown5 = parser.ReadColumn< int >( 5 );
            Unknown6 = parser.ReadColumn< int >( 6 );
            Unknown7 = parser.ReadColumn< int >( 7 );
            Unknown8 = parser.ReadColumn< int >( 8 );
            Unknown9 = parser.ReadColumn< int >( 9 );
            Unknown10 = parser.ReadColumn< int >( 10 );
            Unknown11 = parser.ReadColumn< int >( 11 );
            Unknown12 = parser.ReadColumn< int >( 12 );
            Unknown13 = parser.ReadColumn< int >( 13 );
            Unknown14 = parser.ReadColumn< int >( 14 );
            Unknown15 = parser.ReadColumn< int >( 15 );
            Unknown16 = parser.ReadColumn< int >( 16 );
            Unknown17 = parser.ReadColumn< int >( 17 );
            Unknown18 = parser.ReadColumn< int >( 18 );
            Unknown19 = parser.ReadColumn< int >( 19 );
            Unknown20 = parser.ReadColumn< int >( 20 );
            Unknown21 = parser.ReadColumn< int >( 21 );
            Unknown22 = parser.ReadColumn< int >( 22 );
            Unknown23 = parser.ReadColumn< int >( 23 );
            Unknown24 = parser.ReadColumn< int >( 24 );
            Unknown25 = parser.ReadColumn< int >( 25 );
            Unknown26 = parser.ReadColumn< int >( 26 );
            Unknown27 = parser.ReadColumn< int >( 27 );
            Unknown28 = parser.ReadColumn< int >( 28 );
            Unknown29 = parser.ReadColumn< int >( 29 );
            Unknown30 = parser.ReadColumn< int >( 30 );
            Unknown31 = parser.ReadColumn< int >( 31 );
            Unknown32 = parser.ReadColumn< int >( 32 );
            Unknown33 = parser.ReadColumn< int >( 33 );
            Unknown34 = parser.ReadColumn< int >( 34 );
            Unknown35 = parser.ReadColumn< int >( 35 );
            Unknown36 = parser.ReadColumn< int >( 36 );
            Unknown37 = parser.ReadColumn< int >( 37 );
            Unknown38 = parser.ReadColumn< int >( 38 );
            Unknown39 = parser.ReadColumn< int >( 39 );
            Unknown40 = parser.ReadColumn< int >( 40 );
            Unknown41 = parser.ReadColumn< int >( 41 );
            Unknown42 = parser.ReadColumn< int >( 42 );
            Unknown43 = parser.ReadColumn< int >( 43 );
            Unknown44 = parser.ReadColumn< int >( 44 );
            Unknown45 = parser.ReadColumn< int >( 45 );
            Unknown46 = parser.ReadColumn< int >( 46 );
            Unknown47 = parser.ReadColumn< int >( 47 );
            Unknown48 = parser.ReadColumn< int >( 48 );
            Unknown49 = parser.ReadColumn< int >( 49 );
            Unknown50 = parser.ReadColumn< int >( 50 );
            Unknown51 = parser.ReadColumn< int >( 51 );
            Unknown52 = parser.ReadColumn< int >( 52 );
            Unknown53 = parser.ReadColumn< int >( 53 );
            Unknown54 = parser.ReadColumn< int >( 54 );
            Unknown55 = parser.ReadColumn< int >( 55 );
            Unknown56 = parser.ReadColumn< int >( 56 );
            Unknown57 = parser.ReadColumn< byte >( 57 );
            Unknown58 = parser.ReadColumn< byte >( 58 );
            Unknown59 = parser.ReadColumn< byte >( 59 );
            Unknown60 = parser.ReadColumn< byte >( 60 );
            Unknown61 = parser.ReadColumn< byte >( 61 );
            Unknown62 = parser.ReadColumn< byte >( 62 );
            Unknown63 = parser.ReadColumn< byte >( 63 );
            Unknown64 = parser.ReadColumn< byte >( 64 );
            Unknown65 = parser.ReadColumn< byte >( 65 );
            Unknown66 = parser.ReadColumn< byte >( 66 );
            Unknown67 = parser.ReadColumn< byte >( 67 );
            Unknown68 = parser.ReadColumn< byte >( 68 );
            Unknown69 = parser.ReadColumn< byte >( 69 );
            Unknown70 = parser.ReadColumn< byte >( 70 );
            Unknown71 = parser.ReadColumn< byte >( 71 );
            Unknown72 = parser.ReadColumn< byte >( 72 );
            Unknown73 = parser.ReadColumn< byte >( 73 );
            Unknown74 = parser.ReadColumn< byte >( 74 );
            Unknown75 = parser.ReadColumn< byte >( 75 );
            Unknown76 = parser.ReadColumn< byte >( 76 );
            Unknown77 = parser.ReadColumn< byte >( 77 );
            Unknown78 = parser.ReadColumn< byte >( 78 );
            Unknown79 = parser.ReadColumn< byte >( 79 );
            Unknown80 = parser.ReadColumn< byte >( 80 );
            Unknown81 = parser.ReadColumn< byte >( 81 );
            Unknown82 = parser.ReadColumn< byte >( 82 );
            Unknown83 = parser.ReadColumn< byte >( 83 );
            Unknown84 = parser.ReadColumn< byte >( 84 );
            Unknown85 = parser.ReadColumn< byte >( 85 );
            Unknown86 = parser.ReadColumn< byte >( 86 );
            Unknown87 = parser.ReadColumn< byte >( 87 );
            Unknown88 = parser.ReadColumn< byte >( 88 );
            Unknown89 = parser.ReadColumn< byte >( 89 );
            Unknown90 = parser.ReadColumn< byte >( 90 );
            Unknown91 = parser.ReadColumn< byte >( 91 );
            Unknown92 = parser.ReadColumn< byte >( 92 );
            Unknown93 = parser.ReadColumn< byte >( 93 );
            Unknown94 = parser.ReadColumn< byte >( 94 );
            Unknown95 = parser.ReadColumn< byte >( 95 );
            Unknown96 = parser.ReadColumn< byte >( 96 );
            Unknown97 = parser.ReadColumn< byte >( 97 );
            Unknown98 = parser.ReadColumn< byte >( 98 );
            Unknown99 = parser.ReadColumn< byte >( 99 );
            Unknown100 = parser.ReadColumn< byte >( 100 );
            Unknown101 = parser.ReadColumn< byte >( 101 );
            Unknown102 = parser.ReadColumn< byte >( 102 );
            Unknown103 = parser.ReadColumn< byte >( 103 );
            Unknown104 = parser.ReadColumn< byte >( 104 );
            Unknown105 = parser.ReadColumn< byte >( 105 );
            Unknown106 = parser.ReadColumn< byte >( 106 );
            Unknown107 = parser.ReadColumn< byte >( 107 );
            Unknown108 = parser.ReadColumn< byte >( 108 );
            Unknown109 = parser.ReadColumn< byte >( 109 );
            Unknown110 = parser.ReadColumn< byte >( 110 );
            Unknown111 = parser.ReadColumn< byte >( 111 );
            Unknown112 = parser.ReadColumn< byte >( 112 );
            Unknown113 = parser.ReadColumn< byte >( 113 );
            Unknown114 = parser.ReadColumn< byte >( 114 );
            Unknown115 = parser.ReadColumn< byte >( 115 );
            Unknown116 = parser.ReadColumn< byte >( 116 );
            Unknown117 = parser.ReadColumn< byte >( 117 );
            Unknown118 = parser.ReadColumn< byte >( 118 );
            Unknown119 = parser.ReadColumn< byte >( 119 );
            Unknown120 = parser.ReadColumn< byte >( 120 );
            Unknown121 = parser.ReadColumn< byte >( 121 );
            Unknown122 = parser.ReadColumn< byte >( 122 );
            Unknown123 = parser.ReadColumn< byte >( 123 );
            Unknown124 = parser.ReadColumn< byte >( 124 );
            Unknown125 = parser.ReadColumn< byte >( 125 );
            Unknown126 = parser.ReadColumn< byte >( 126 );
            Unknown127 = parser.ReadColumn< byte >( 127 );
            Unknown128 = parser.ReadColumn< byte >( 128 );
            Unknown129 = parser.ReadColumn< byte >( 129 );
            Unknown130 = parser.ReadColumn< byte >( 130 );
            Unknown131 = parser.ReadColumn< byte >( 131 );
            Unknown132 = parser.ReadColumn< byte >( 132 );
            Unknown133 = parser.ReadColumn< byte >( 133 );
            Unknown134 = parser.ReadColumn< byte >( 134 );
            Unknown135 = parser.ReadColumn< byte >( 135 );
            Unknown136 = parser.ReadColumn< byte >( 136 );
            Unknown137 = parser.ReadColumn< byte >( 137 );
            Unknown138 = parser.ReadColumn< byte >( 138 );
            Unknown139 = parser.ReadColumn< byte >( 139 );
            Unknown140 = parser.ReadColumn< byte >( 140 );
            Unknown141 = parser.ReadColumn< byte >( 141 );
            Unknown142 = parser.ReadColumn< byte >( 142 );
            Unknown143 = parser.ReadColumn< byte >( 143 );
            Unknown144 = parser.ReadColumn< byte >( 144 );
            Unknown145 = parser.ReadColumn< byte >( 145 );
            Unknown146 = parser.ReadColumn< byte >( 146 );
            Unknown147 = parser.ReadColumn< byte >( 147 );
            Unknown148 = parser.ReadColumn< byte >( 148 );
            Unknown149 = parser.ReadColumn< byte >( 149 );
            Unknown150 = parser.ReadColumn< byte >( 150 );
            Unknown151 = parser.ReadColumn< byte >( 151 );
            Unknown152 = parser.ReadColumn< byte >( 152 );
            Unknown153 = parser.ReadColumn< byte >( 153 );
            Unknown154 = parser.ReadColumn< byte >( 154 );
            Unknown155 = parser.ReadColumn< byte >( 155 );
            Unknown156 = parser.ReadColumn< byte >( 156 );
            Unknown157 = parser.ReadColumn< byte >( 157 );
            Unknown158 = parser.ReadColumn< byte >( 158 );
            Unknown159 = parser.ReadColumn< byte >( 159 );
            Unknown160 = parser.ReadColumn< byte >( 160 );
            Unknown161 = parser.ReadColumn< byte >( 161 );
            Unknown162 = parser.ReadColumn< byte >( 162 );
            Unknown163 = parser.ReadColumn< byte >( 163 );
            Unknown164 = parser.ReadColumn< byte >( 164 );
            Unknown165 = parser.ReadColumn< byte >( 165 );
            Unknown166 = parser.ReadColumn< byte >( 166 );
            Unknown167 = parser.ReadColumn< byte >( 167 );
            Unknown168 = parser.ReadColumn< byte >( 168 );
            Unknown169 = parser.ReadColumn< byte >( 169 );
            Unknown170 = parser.ReadColumn< byte >( 170 );
            Unknown171 = parser.ReadColumn< byte >( 171 );
            Unknown172 = parser.ReadColumn< byte >( 172 );
            Unknown173 = parser.ReadColumn< byte >( 173 );
            Unknown174 = parser.ReadColumn< byte >( 174 );
            Unknown175 = parser.ReadColumn< byte >( 175 );
            Unknown176 = parser.ReadColumn< byte >( 176 );
            Unknown177 = parser.ReadColumn< int >( 177 );
            Unknown178 = parser.ReadColumn< int >( 178 );
            Unknown179 = parser.ReadColumn< int >( 179 );
            Unknown180 = parser.ReadColumn< int >( 180 );
            Unknown181 = parser.ReadColumn< int >( 181 );
            Unknown182 = parser.ReadColumn< int >( 182 );
            Unknown183 = parser.ReadColumn< int >( 183 );
            Unknown184 = parser.ReadColumn< int >( 184 );
            Unknown185 = parser.ReadColumn< int >( 185 );
            Unknown186 = parser.ReadColumn< int >( 186 );
            Unknown187 = parser.ReadColumn< int >( 187 );
            Unknown188 = parser.ReadColumn< int >( 188 );
            Unknown189 = parser.ReadColumn< int >( 189 );
            Unknown190 = parser.ReadColumn< int >( 190 );
            Unknown191 = parser.ReadColumn< int >( 191 );
            Unknown192 = parser.ReadColumn< int >( 192 );
            Unknown193 = parser.ReadColumn< int >( 193 );
            Unknown194 = parser.ReadColumn< int >( 194 );
            Unknown195 = parser.ReadColumn< int >( 195 );
            Unknown196 = parser.ReadColumn< int >( 196 );
            Unknown197 = parser.ReadColumn< int >( 197 );
            Unknown198 = parser.ReadColumn< int >( 198 );
            Unknown199 = parser.ReadColumn< int >( 199 );
            Unknown200 = parser.ReadColumn< int >( 200 );
            Unknown201 = parser.ReadColumn< int >( 201 );
            Unknown202 = parser.ReadColumn< int >( 202 );
            Unknown203 = parser.ReadColumn< int >( 203 );
            Unknown204 = parser.ReadColumn< int >( 204 );
            Unknown205 = parser.ReadColumn< int >( 205 );
            Unknown206 = parser.ReadColumn< int >( 206 );
            Unknown207 = parser.ReadColumn< int >( 207 );
            Unknown208 = parser.ReadColumn< int >( 208 );
            Unknown209 = parser.ReadColumn< int >( 209 );
            Unknown210 = parser.ReadColumn< int >( 210 );
            Unknown211 = parser.ReadColumn< int >( 211 );
            Unknown212 = parser.ReadColumn< int >( 212 );
            Unknown213 = parser.ReadColumn< int >( 213 );
            Unknown214 = parser.ReadColumn< int >( 214 );
            Unknown215 = parser.ReadColumn< int >( 215 );
            Unknown216 = parser.ReadColumn< int >( 216 );
            Unknown217 = parser.ReadColumn< int >( 217 );
            Unknown218 = parser.ReadColumn< int >( 218 );
            Unknown219 = parser.ReadColumn< int >( 219 );
            Unknown220 = parser.ReadColumn< int >( 220 );
            Unknown221 = parser.ReadColumn< int >( 221 );
            Unknown222 = parser.ReadColumn< int >( 222 );
            Unknown223 = parser.ReadColumn< int >( 223 );
            Unknown224 = parser.ReadColumn< int >( 224 );
            Unknown225 = parser.ReadColumn< int >( 225 );
            Unknown226 = parser.ReadColumn< int >( 226 );
            Unknown227 = parser.ReadColumn< int >( 227 );
            Unknown228 = parser.ReadColumn< int >( 228 );
            Unknown229 = parser.ReadColumn< int >( 229 );
            Unknown230 = parser.ReadColumn< int >( 230 );
            Unknown231 = parser.ReadColumn< int >( 231 );
            Unknown232 = parser.ReadColumn< int >( 232 );
            Unknown233 = parser.ReadColumn< int >( 233 );
            Unknown234 = parser.ReadColumn< int >( 234 );
            Unknown235 = parser.ReadColumn< int >( 235 );
            Unknown236 = parser.ReadColumn< int >( 236 );
            Unknown237 = parser.ReadColumn< int >( 237 );
            Unknown238 = parser.ReadColumn< int >( 238 );
            Unknown239 = parser.ReadColumn< int >( 239 );
            Unknown240 = parser.ReadColumn< int >( 240 );
            Unknown241 = parser.ReadColumn< int >( 241 );
            Unknown242 = parser.ReadColumn< int >( 242 );
            Unknown243 = parser.ReadColumn< int >( 243 );
            Unknown244 = parser.ReadColumn< int >( 244 );
            Unknown245 = parser.ReadColumn< int >( 245 );
            Unknown246 = parser.ReadColumn< int >( 246 );
            Unknown247 = parser.ReadColumn< int >( 247 );
            Unknown248 = parser.ReadColumn< int >( 248 );
            Unknown249 = parser.ReadColumn< int >( 249 );
            Unknown250 = parser.ReadColumn< int >( 250 );
            Unknown251 = parser.ReadColumn< int >( 251 );
            Unknown252 = parser.ReadColumn< int >( 252 );
            Unknown253 = parser.ReadColumn< int >( 253 );
            Unknown254 = parser.ReadColumn< int >( 254 );
            Unknown255 = parser.ReadColumn< int >( 255 );
            Unknown256 = parser.ReadColumn< int >( 256 );
            Unknown257 = parser.ReadColumn< int >( 257 );
            Unknown258 = parser.ReadColumn< int >( 258 );
            Unknown259 = parser.ReadColumn< int >( 259 );
            Unknown260 = parser.ReadColumn< int >( 260 );
            Unknown261 = parser.ReadColumn< int >( 261 );
            Unknown262 = parser.ReadColumn< int >( 262 );
            Unknown263 = parser.ReadColumn< int >( 263 );
            Unknown264 = parser.ReadColumn< int >( 264 );
            Unknown265 = parser.ReadColumn< int >( 265 );
            Unknown266 = parser.ReadColumn< int >( 266 );
            Unknown267 = parser.ReadColumn< int >( 267 );
            Unknown268 = parser.ReadColumn< int >( 268 );
            Unknown269 = parser.ReadColumn< int >( 269 );
            Unknown270 = parser.ReadColumn< int >( 270 );
            Unknown271 = parser.ReadColumn< int >( 271 );
            Unknown272 = parser.ReadColumn< int >( 272 );
        }
    }
}