// ReSharper disable All

using Lumina.Text;
using Lumina.Data;
using Lumina.Data.Structs.Excel;

namespace Lumina.Excel.GeneratedSheets
{
    [Sheet( "Frontline04", columnHash: 0x26885afa )]
    public class Frontline04 : ExcelRow
    {
        
        public LazyRow< Level > Level1 { get; set; }
        public LazyRow< Level > Level2 { get; set; }
        public LazyRow< Level > Level3 { get; set; }
        public int Unknown3 { get; set; }
        public int Unknown4 { get; set; }
        public int Unknown5 { get; set; }
        public int Unknown6 { get; set; }
        public int Unknown7 { get; set; }
        public int Unknown8 { get; set; }
        public int Unknown9 { get; set; }
        public int Unknown10 { get; set; }
        public int Unknown11 { get; set; }
        public int Unknown12 { get; set; }
        public int Unknown13 { get; set; }
        public int Unknown14 { get; set; }
        public int Unknown15 { get; set; }
        public int Unknown16 { get; set; }
        public int Unknown17 { get; set; }
        public int Unknown18 { get; set; }
        public int Unknown19 { get; set; }
        public int Unknown20 { get; set; }
        public int Unknown21 { get; set; }
        public int Unknown22 { get; set; }
        public int Unknown23 { get; set; }
        public int Unknown24 { get; set; }
        public int Unknown25 { get; set; }
        public int Unknown26 { get; set; }
        public int Unknown27 { get; set; }
        public int Unknown28 { get; set; }
        public int Unknown29 { get; set; }
        public int Unknown30 { get; set; }
        public int Unknown31 { get; set; }
        public int Unknown32 { get; set; }
        public int Unknown33 { get; set; }
        public int Unknown34 { get; set; }
        public int Unknown35 { get; set; }
        public int Unknown36 { get; set; }
        public int Unknown37 { get; set; }
        public int Unknown38 { get; set; }
        public int Unknown39 { get; set; }
        public int Unknown40 { get; set; }
        public int Unknown41 { get; set; }
        public int Unknown42 { get; set; }
        public int Unknown43 { get; set; }
        public int Unknown44 { get; set; }
        public int Unknown45 { get; set; }
        public int Unknown46 { get; set; }
        public int Unknown47 { get; set; }
        public int Unknown48 { get; set; }
        public int Unknown49 { get; set; }
        public int Unknown50 { get; set; }
        public int Unknown51 { get; set; }
        public int Unknown52 { get; set; }
        public int Unknown53 { get; set; }
        public int Unknown54 { get; set; }
        public int Unknown55 { get; set; }
        public int Unknown56 { get; set; }
        public int Unknown57 { get; set; }
        public int Unknown58 { get; set; }
        public int Unknown59 { get; set; }
        public int Unknown60 { get; set; }
        public int Unknown61 { get; set; }
        public int Unknown62 { get; set; }
        public int Unknown63 { get; set; }
        public int Unknown64 { get; set; }
        public int Unknown65 { get; set; }
        public int Unknown66 { get; set; }
        public int Unknown67 { get; set; }
        public int Unknown68 { get; set; }
        public int Unknown69 { get; set; }
        public int Unknown70 { get; set; }
        public int Unknown71 { get; set; }
        public int Unknown72 { get; set; }
        public int Unknown73 { get; set; }
        public int Unknown74 { get; set; }
        public int Unknown75 { get; set; }
        public int Unknown76 { get; set; }
        public int Unknown77 { get; set; }
        public int Unknown78 { get; set; }
        public int Unknown79 { get; set; }
        public int Unknown80 { get; set; }
        public int Unknown81 { get; set; }
        public int Unknown82 { get; set; }
        public int Unknown83 { get; set; }
        public int Unknown84 { get; set; }
        public int Unknown85 { get; set; }
        public int Unknown86 { get; set; }
        public int Unknown87 { get; set; }
        public int Unknown88 { get; set; }
        public byte Unknown89 { get; set; }
        public byte Unknown90 { get; set; }
        public byte Unknown91 { get; set; }
        public byte Unknown92 { get; set; }
        public byte Unknown93 { get; set; }
        public byte Unknown94 { get; set; }
        public byte Unknown95 { get; set; }
        public byte Unknown96 { get; set; }
        public byte Unknown97 { get; set; }
        public byte Unknown98 { get; set; }
        public byte Unknown99 { get; set; }
        public byte Unknown100 { get; set; }
        public byte Unknown101 { get; set; }
        public byte Unknown102 { get; set; }
        public byte Unknown103 { get; set; }
        public byte Unknown104 { get; set; }
        public byte Unknown105 { get; set; }
        public byte Unknown106 { get; set; }
        public byte Unknown107 { get; set; }
        public byte Unknown108 { get; set; }
        public byte Unknown109 { get; set; }
        public byte Unknown110 { get; set; }
        public byte Unknown111 { get; set; }
        public byte Unknown112 { get; set; }
        public byte Unknown113 { get; set; }
        public byte Unknown114 { get; set; }
        public byte Unknown115 { get; set; }
        public byte Unknown116 { get; set; }
        public byte Unknown117 { get; set; }
        public byte Unknown118 { get; set; }
        public byte Unknown119 { get; set; }
        public byte Unknown120 { get; set; }
        public byte Unknown121 { get; set; }
        public byte Unknown122 { get; set; }
        public byte Unknown123 { get; set; }
        public byte Unknown124 { get; set; }
        public byte Unknown125 { get; set; }
        public byte Unknown126 { get; set; }
        public byte Unknown127 { get; set; }
        public byte Unknown128 { get; set; }
        public byte Unknown129 { get; set; }
        public byte Unknown130 { get; set; }
        public byte Unknown131 { get; set; }
        public byte Unknown132 { get; set; }
        public byte Unknown133 { get; set; }
        public byte Unknown134 { get; set; }
        public byte Unknown135 { get; set; }
        public byte Unknown136 { get; set; }
        public byte Unknown137 { get; set; }
        public byte Unknown138 { get; set; }
        public byte Unknown139 { get; set; }
        public byte Unknown140 { get; set; }
        public byte Unknown141 { get; set; }
        public byte Unknown142 { get; set; }
        public byte Unknown143 { get; set; }
        public byte Unknown144 { get; set; }
        public byte Unknown145 { get; set; }
        public byte Unknown146 { get; set; }
        public byte Unknown147 { get; set; }
        public byte Unknown148 { get; set; }
        public byte Unknown149 { get; set; }
        public byte Unknown150 { get; set; }
        public byte Unknown151 { get; set; }
        public byte Unknown152 { get; set; }
        public byte Unknown153 { get; set; }
        public byte Unknown154 { get; set; }
        public byte Unknown155 { get; set; }
        public byte Unknown156 { get; set; }
        public byte Unknown157 { get; set; }
        public byte Unknown158 { get; set; }
        public byte Unknown159 { get; set; }
        public byte Unknown160 { get; set; }
        public byte Unknown161 { get; set; }
        public byte Unknown162 { get; set; }
        public byte Unknown163 { get; set; }
        public byte Unknown164 { get; set; }
        public byte Unknown165 { get; set; }
        public byte Unknown166 { get; set; }
        public byte Unknown167 { get; set; }
        public byte Unknown168 { get; set; }
        public byte Unknown169 { get; set; }
        public byte Unknown170 { get; set; }
        public byte Unknown171 { get; set; }
        public byte Unknown172 { get; set; }
        public byte Unknown173 { get; set; }
        public byte Unknown174 { get; set; }
        public byte Unknown175 { get; set; }
        public byte Unknown176 { get; set; }
        public byte Unknown177 { get; set; }
        public byte Unknown178 { get; set; }
        public byte Unknown179 { get; set; }
        public byte Unknown180 { get; set; }
        public byte Unknown181 { get; set; }
        public byte Unknown182 { get; set; }
        public byte Unknown183 { get; set; }
        public byte Unknown184 { get; set; }
        public byte Unknown185 { get; set; }
        public byte Unknown186 { get; set; }
        public byte Unknown187 { get; set; }
        public byte Unknown188 { get; set; }
        public byte Unknown189 { get; set; }
        public byte Unknown190 { get; set; }
        public byte Unknown191 { get; set; }
        public byte Unknown192 { get; set; }
        public byte Unknown193 { get; set; }
        public byte Unknown194 { get; set; }
        public byte Unknown195 { get; set; }
        public byte Unknown196 { get; set; }
        public byte Unknown197 { get; set; }
        public byte Unknown198 { get; set; }
        public byte Unknown199 { get; set; }
        public byte Unknown200 { get; set; }
        public byte Unknown201 { get; set; }
        public byte Unknown202 { get; set; }
        public byte Unknown203 { get; set; }
        public byte Unknown204 { get; set; }
        public byte Unknown205 { get; set; }
        public byte Unknown206 { get; set; }
        public byte Unknown207 { get; set; }
        public byte Unknown208 { get; set; }
        public byte Unknown209 { get; set; }
        public byte Unknown210 { get; set; }
        public byte Unknown211 { get; set; }
        public byte Unknown212 { get; set; }
        public byte Unknown213 { get; set; }
        public byte Unknown214 { get; set; }
        public byte Unknown215 { get; set; }
        public byte Unknown216 { get; set; }
        public byte Unknown217 { get; set; }
        public byte Unknown218 { get; set; }
        public byte Unknown219 { get; set; }
        public byte Unknown220 { get; set; }
        public byte Unknown221 { get; set; }
        public byte Unknown222 { get; set; }
        public byte Unknown223 { get; set; }
        public byte Unknown224 { get; set; }
        public byte Unknown225 { get; set; }
        public byte Unknown226 { get; set; }
        public byte Unknown227 { get; set; }
        public byte Unknown228 { get; set; }
        public byte Unknown229 { get; set; }
        public byte Unknown230 { get; set; }
        public byte Unknown231 { get; set; }
        public byte Unknown232 { get; set; }
        public byte Unknown233 { get; set; }
        public byte Unknown234 { get; set; }
        public byte Unknown235 { get; set; }
        public byte Unknown236 { get; set; }
        public byte Unknown237 { get; set; }
        public byte Unknown238 { get; set; }
        public byte Unknown239 { get; set; }
        public byte Unknown240 { get; set; }
        public byte Unknown241 { get; set; }
        public byte Unknown242 { get; set; }
        public byte Unknown243 { get; set; }
        public byte Unknown244 { get; set; }
        public byte Unknown245 { get; set; }
        public byte Unknown246 { get; set; }
        public byte Unknown247 { get; set; }
        public byte Unknown248 { get; set; }
        public byte Unknown249 { get; set; }
        public byte Unknown250 { get; set; }
        public byte Unknown251 { get; set; }
        public byte Unknown252 { get; set; }
        public byte Unknown253 { get; set; }
        public byte Unknown254 { get; set; }
        public byte Unknown255 { get; set; }
        public byte Unknown256 { get; set; }
        public byte Unknown257 { get; set; }
        public byte Unknown258 { get; set; }
        public byte Unknown259 { get; set; }
        public byte Unknown260 { get; set; }
        public byte Unknown261 { get; set; }
        public byte Unknown262 { get; set; }
        public byte Unknown263 { get; set; }
        public byte Unknown264 { get; set; }
        public byte Unknown265 { get; set; }
        public byte Unknown266 { get; set; }
        public byte Unknown267 { get; set; }
        public byte Unknown268 { get; set; }
        public byte Unknown269 { get; set; }
        public byte Unknown270 { get; set; }
        public byte Unknown271 { get; set; }
        public byte Unknown272 { get; set; }
        public int Unknown273 { get; set; }
        public int Unknown274 { get; set; }
        public int Unknown275 { get; set; }
        public int Unknown276 { get; set; }
        public int Unknown277 { get; set; }
        public int Unknown278 { get; set; }
        public int Unknown279 { get; set; }
        public int Unknown280 { get; set; }
        public int Unknown281 { get; set; }
        public int Unknown282 { get; set; }
        public int Unknown283 { get; set; }
        public int Unknown284 { get; set; }
        public int Unknown285 { get; set; }
        public int Unknown286 { get; set; }
        public int Unknown287 { get; set; }
        public int Unknown288 { get; set; }
        public int Unknown289 { get; set; }
        public int Unknown290 { get; set; }
        public int Unknown291 { get; set; }
        public int Unknown292 { get; set; }
        public int Unknown293 { get; set; }
        public int Unknown294 { get; set; }
        public int Unknown295 { get; set; }
        public int Unknown296 { get; set; }
        public int Unknown297 { get; set; }
        public int Unknown298 { get; set; }
        public int Unknown299 { get; set; }
        public int Unknown300 { get; set; }
        public int Unknown301 { get; set; }
        public int Unknown302 { get; set; }
        public int Unknown303 { get; set; }
        public int Unknown304 { get; set; }
        public int Unknown305 { get; set; }
        public int Unknown306 { get; set; }
        public int Unknown307 { get; set; }
        public int Unknown308 { get; set; }
        public int Unknown309 { get; set; }
        public int Unknown310 { get; set; }
        public int Unknown311 { get; set; }
        public int Unknown312 { get; set; }
        public int Unknown313 { get; set; }
        public int Unknown314 { get; set; }
        public int Unknown315 { get; set; }
        public int Unknown316 { get; set; }
        public int Unknown317 { get; set; }
        public int Unknown318 { get; set; }
        public int Unknown319 { get; set; }
        public int Unknown320 { get; set; }
        public int Unknown321 { get; set; }
        public int Unknown322 { get; set; }
        public int Unknown323 { get; set; }
        public int Unknown324 { get; set; }
        public int Unknown325 { get; set; }
        public int Unknown326 { get; set; }
        public int Unknown327 { get; set; }
        public int Unknown328 { get; set; }
        public int Unknown329 { get; set; }
        public int Unknown330 { get; set; }
        public int Unknown331 { get; set; }
        public int Unknown332 { get; set; }
        public int Unknown333 { get; set; }
        public int Unknown334 { get; set; }
        public int Unknown335 { get; set; }
        public int Unknown336 { get; set; }
        public int Unknown337 { get; set; }
        public int Unknown338 { get; set; }
        public int Unknown339 { get; set; }
        public int Unknown340 { get; set; }
        public int Unknown341 { get; set; }
        public int Unknown342 { get; set; }
        public int Unknown343 { get; set; }
        public int Unknown344 { get; set; }
        public int Unknown345 { get; set; }
        public int Unknown346 { get; set; }
        public int Unknown347 { get; set; }
        public int Unknown348 { get; set; }
        public int Unknown349 { get; set; }
        public int Unknown350 { get; set; }
        public int Unknown351 { get; set; }
        public int Unknown352 { get; set; }
        public int Unknown353 { get; set; }
        public int Unknown354 { get; set; }
        public int Unknown355 { get; set; }
        public int Unknown356 { get; set; }
        public int Unknown357 { get; set; }
        public int Unknown358 { get; set; }
        public int Unknown359 { get; set; }
        public int Unknown360 { get; set; }
        public int Unknown361 { get; set; }
        public int Unknown362 { get; set; }
        public int Unknown363 { get; set; }
        public int Unknown364 { get; set; }
        public int Unknown365 { get; set; }
        public int Unknown366 { get; set; }
        public int Unknown367 { get; set; }
        public int Unknown368 { get; set; }
        
        public override void PopulateData( RowParser parser, GameData gameData, Language language )
        {
            base.PopulateData( parser, gameData, language );

            Level1 = new LazyRow< Level >( gameData, parser.ReadColumn< int >( 0 ), language );
            Level2 = new LazyRow< Level >( gameData, parser.ReadColumn< int >( 1 ), language );
            Level3 = new LazyRow< Level >( gameData, parser.ReadColumn< int >( 2 ), language );
            Unknown3 = parser.ReadColumn< int >( 3 );
            Unknown4 = parser.ReadColumn< int >( 4 );
            Unknown5 = parser.ReadColumn< int >( 5 );
            Unknown6 = parser.ReadColumn< int >( 6 );
            Unknown7 = parser.ReadColumn< int >( 7 );
            Unknown8 = parser.ReadColumn< int >( 8 );
            Unknown9 = parser.ReadColumn< int >( 9 );
            Unknown10 = parser.ReadColumn< int >( 10 );
            Unknown11 = parser.ReadColumn< int >( 11 );
            Unknown12 = parser.ReadColumn< int >( 12 );
            Unknown13 = parser.ReadColumn< int >( 13 );
            Unknown14 = parser.ReadColumn< int >( 14 );
            Unknown15 = parser.ReadColumn< int >( 15 );
            Unknown16 = parser.ReadColumn< int >( 16 );
            Unknown17 = parser.ReadColumn< int >( 17 );
            Unknown18 = parser.ReadColumn< int >( 18 );
            Unknown19 = parser.ReadColumn< int >( 19 );
            Unknown20 = parser.ReadColumn< int >( 20 );
            Unknown21 = parser.ReadColumn< int >( 21 );
            Unknown22 = parser.ReadColumn< int >( 22 );
            Unknown23 = parser.ReadColumn< int >( 23 );
            Unknown24 = parser.ReadColumn< int >( 24 );
            Unknown25 = parser.ReadColumn< int >( 25 );
            Unknown26 = parser.ReadColumn< int >( 26 );
            Unknown27 = parser.ReadColumn< int >( 27 );
            Unknown28 = parser.ReadColumn< int >( 28 );
            Unknown29 = parser.ReadColumn< int >( 29 );
            Unknown30 = parser.ReadColumn< int >( 30 );
            Unknown31 = parser.ReadColumn< int >( 31 );
            Unknown32 = parser.ReadColumn< int >( 32 );
            Unknown33 = parser.ReadColumn< int >( 33 );
            Unknown34 = parser.ReadColumn< int >( 34 );
            Unknown35 = parser.ReadColumn< int >( 35 );
            Unknown36 = parser.ReadColumn< int >( 36 );
            Unknown37 = parser.ReadColumn< int >( 37 );
            Unknown38 = parser.ReadColumn< int >( 38 );
            Unknown39 = parser.ReadColumn< int >( 39 );
            Unknown40 = parser.ReadColumn< int >( 40 );
            Unknown41 = parser.ReadColumn< int >( 41 );
            Unknown42 = parser.ReadColumn< int >( 42 );
            Unknown43 = parser.ReadColumn< int >( 43 );
            Unknown44 = parser.ReadColumn< int >( 44 );
            Unknown45 = parser.ReadColumn< int >( 45 );
            Unknown46 = parser.ReadColumn< int >( 46 );
            Unknown47 = parser.ReadColumn< int >( 47 );
            Unknown48 = parser.ReadColumn< int >( 48 );
            Unknown49 = parser.ReadColumn< int >( 49 );
            Unknown50 = parser.ReadColumn< int >( 50 );
            Unknown51 = parser.ReadColumn< int >( 51 );
            Unknown52 = parser.ReadColumn< int >( 52 );
            Unknown53 = parser.ReadColumn< int >( 53 );
            Unknown54 = parser.ReadColumn< int >( 54 );
            Unknown55 = parser.ReadColumn< int >( 55 );
            Unknown56 = parser.ReadColumn< int >( 56 );
            Unknown57 = parser.ReadColumn< int >( 57 );
            Unknown58 = parser.ReadColumn< int >( 58 );
            Unknown59 = parser.ReadColumn< int >( 59 );
            Unknown60 = parser.ReadColumn< int >( 60 );
            Unknown61 = parser.ReadColumn< int >( 61 );
            Unknown62 = parser.ReadColumn< int >( 62 );
            Unknown63 = parser.ReadColumn< int >( 63 );
            Unknown64 = parser.ReadColumn< int >( 64 );
            Unknown65 = parser.ReadColumn< int >( 65 );
            Unknown66 = parser.ReadColumn< int >( 66 );
            Unknown67 = parser.ReadColumn< int >( 67 );
            Unknown68 = parser.ReadColumn< int >( 68 );
            Unknown69 = parser.ReadColumn< int >( 69 );
            Unknown70 = parser.ReadColumn< int >( 70 );
            Unknown71 = parser.ReadColumn< int >( 71 );
            Unknown72 = parser.ReadColumn< int >( 72 );
            Unknown73 = parser.ReadColumn< int >( 73 );
            Unknown74 = parser.ReadColumn< int >( 74 );
            Unknown75 = parser.ReadColumn< int >( 75 );
            Unknown76 = parser.ReadColumn< int >( 76 );
            Unknown77 = parser.ReadColumn< int >( 77 );
            Unknown78 = parser.ReadColumn< int >( 78 );
            Unknown79 = parser.ReadColumn< int >( 79 );
            Unknown80 = parser.ReadColumn< int >( 80 );
            Unknown81 = parser.ReadColumn< int >( 81 );
            Unknown82 = parser.ReadColumn< int >( 82 );
            Unknown83 = parser.ReadColumn< int >( 83 );
            Unknown84 = parser.ReadColumn< int >( 84 );
            Unknown85 = parser.ReadColumn< int >( 85 );
            Unknown86 = parser.ReadColumn< int >( 86 );
            Unknown87 = parser.ReadColumn< int >( 87 );
            Unknown88 = parser.ReadColumn< int >( 88 );
            Unknown89 = parser.ReadColumn< byte >( 89 );
            Unknown90 = parser.ReadColumn< byte >( 90 );
            Unknown91 = parser.ReadColumn< byte >( 91 );
            Unknown92 = parser.ReadColumn< byte >( 92 );
            Unknown93 = parser.ReadColumn< byte >( 93 );
            Unknown94 = parser.ReadColumn< byte >( 94 );
            Unknown95 = parser.ReadColumn< byte >( 95 );
            Unknown96 = parser.ReadColumn< byte >( 96 );
            Unknown97 = parser.ReadColumn< byte >( 97 );
            Unknown98 = parser.ReadColumn< byte >( 98 );
            Unknown99 = parser.ReadColumn< byte >( 99 );
            Unknown100 = parser.ReadColumn< byte >( 100 );
            Unknown101 = parser.ReadColumn< byte >( 101 );
            Unknown102 = parser.ReadColumn< byte >( 102 );
            Unknown103 = parser.ReadColumn< byte >( 103 );
            Unknown104 = parser.ReadColumn< byte >( 104 );
            Unknown105 = parser.ReadColumn< byte >( 105 );
            Unknown106 = parser.ReadColumn< byte >( 106 );
            Unknown107 = parser.ReadColumn< byte >( 107 );
            Unknown108 = parser.ReadColumn< byte >( 108 );
            Unknown109 = parser.ReadColumn< byte >( 109 );
            Unknown110 = parser.ReadColumn< byte >( 110 );
            Unknown111 = parser.ReadColumn< byte >( 111 );
            Unknown112 = parser.ReadColumn< byte >( 112 );
            Unknown113 = parser.ReadColumn< byte >( 113 );
            Unknown114 = parser.ReadColumn< byte >( 114 );
            Unknown115 = parser.ReadColumn< byte >( 115 );
            Unknown116 = parser.ReadColumn< byte >( 116 );
            Unknown117 = parser.ReadColumn< byte >( 117 );
            Unknown118 = parser.ReadColumn< byte >( 118 );
            Unknown119 = parser.ReadColumn< byte >( 119 );
            Unknown120 = parser.ReadColumn< byte >( 120 );
            Unknown121 = parser.ReadColumn< byte >( 121 );
            Unknown122 = parser.ReadColumn< byte >( 122 );
            Unknown123 = parser.ReadColumn< byte >( 123 );
            Unknown124 = parser.ReadColumn< byte >( 124 );
            Unknown125 = parser.ReadColumn< byte >( 125 );
            Unknown126 = parser.ReadColumn< byte >( 126 );
            Unknown127 = parser.ReadColumn< byte >( 127 );
            Unknown128 = parser.ReadColumn< byte >( 128 );
            Unknown129 = parser.ReadColumn< byte >( 129 );
            Unknown130 = parser.ReadColumn< byte >( 130 );
            Unknown131 = parser.ReadColumn< byte >( 131 );
            Unknown132 = parser.ReadColumn< byte >( 132 );
            Unknown133 = parser.ReadColumn< byte >( 133 );
            Unknown134 = parser.ReadColumn< byte >( 134 );
            Unknown135 = parser.ReadColumn< byte >( 135 );
            Unknown136 = parser.ReadColumn< byte >( 136 );
            Unknown137 = parser.ReadColumn< byte >( 137 );
            Unknown138 = parser.ReadColumn< byte >( 138 );
            Unknown139 = parser.ReadColumn< byte >( 139 );
            Unknown140 = parser.ReadColumn< byte >( 140 );
            Unknown141 = parser.ReadColumn< byte >( 141 );
            Unknown142 = parser.ReadColumn< byte >( 142 );
            Unknown143 = parser.ReadColumn< byte >( 143 );
            Unknown144 = parser.ReadColumn< byte >( 144 );
            Unknown145 = parser.ReadColumn< byte >( 145 );
            Unknown146 = parser.ReadColumn< byte >( 146 );
            Unknown147 = parser.ReadColumn< byte >( 147 );
            Unknown148 = parser.ReadColumn< byte >( 148 );
            Unknown149 = parser.ReadColumn< byte >( 149 );
            Unknown150 = parser.ReadColumn< byte >( 150 );
            Unknown151 = parser.ReadColumn< byte >( 151 );
            Unknown152 = parser.ReadColumn< byte >( 152 );
            Unknown153 = parser.ReadColumn< byte >( 153 );
            Unknown154 = parser.ReadColumn< byte >( 154 );
            Unknown155 = parser.ReadColumn< byte >( 155 );
            Unknown156 = parser.ReadColumn< byte >( 156 );
            Unknown157 = parser.ReadColumn< byte >( 157 );
            Unknown158 = parser.ReadColumn< byte >( 158 );
            Unknown159 = parser.ReadColumn< byte >( 159 );
            Unknown160 = parser.ReadColumn< byte >( 160 );
            Unknown161 = parser.ReadColumn< byte >( 161 );
            Unknown162 = parser.ReadColumn< byte >( 162 );
            Unknown163 = parser.ReadColumn< byte >( 163 );
            Unknown164 = parser.ReadColumn< byte >( 164 );
            Unknown165 = parser.ReadColumn< byte >( 165 );
            Unknown166 = parser.ReadColumn< byte >( 166 );
            Unknown167 = parser.ReadColumn< byte >( 167 );
            Unknown168 = parser.ReadColumn< byte >( 168 );
            Unknown169 = parser.ReadColumn< byte >( 169 );
            Unknown170 = parser.ReadColumn< byte >( 170 );
            Unknown171 = parser.ReadColumn< byte >( 171 );
            Unknown172 = parser.ReadColumn< byte >( 172 );
            Unknown173 = parser.ReadColumn< byte >( 173 );
            Unknown174 = parser.ReadColumn< byte >( 174 );
            Unknown175 = parser.ReadColumn< byte >( 175 );
            Unknown176 = parser.ReadColumn< byte >( 176 );
            Unknown177 = parser.ReadColumn< byte >( 177 );
            Unknown178 = parser.ReadColumn< byte >( 178 );
            Unknown179 = parser.ReadColumn< byte >( 179 );
            Unknown180 = parser.ReadColumn< byte >( 180 );
            Unknown181 = parser.ReadColumn< byte >( 181 );
            Unknown182 = parser.ReadColumn< byte >( 182 );
            Unknown183 = parser.ReadColumn< byte >( 183 );
            Unknown184 = parser.ReadColumn< byte >( 184 );
            Unknown185 = parser.ReadColumn< byte >( 185 );
            Unknown186 = parser.ReadColumn< byte >( 186 );
            Unknown187 = parser.ReadColumn< byte >( 187 );
            Unknown188 = parser.ReadColumn< byte >( 188 );
            Unknown189 = parser.ReadColumn< byte >( 189 );
            Unknown190 = parser.ReadColumn< byte >( 190 );
            Unknown191 = parser.ReadColumn< byte >( 191 );
            Unknown192 = parser.ReadColumn< byte >( 192 );
            Unknown193 = parser.ReadColumn< byte >( 193 );
            Unknown194 = parser.ReadColumn< byte >( 194 );
            Unknown195 = parser.ReadColumn< byte >( 195 );
            Unknown196 = parser.ReadColumn< byte >( 196 );
            Unknown197 = parser.ReadColumn< byte >( 197 );
            Unknown198 = parser.ReadColumn< byte >( 198 );
            Unknown199 = parser.ReadColumn< byte >( 199 );
            Unknown200 = parser.ReadColumn< byte >( 200 );
            Unknown201 = parser.ReadColumn< byte >( 201 );
            Unknown202 = parser.ReadColumn< byte >( 202 );
            Unknown203 = parser.ReadColumn< byte >( 203 );
            Unknown204 = parser.ReadColumn< byte >( 204 );
            Unknown205 = parser.ReadColumn< byte >( 205 );
            Unknown206 = parser.ReadColumn< byte >( 206 );
            Unknown207 = parser.ReadColumn< byte >( 207 );
            Unknown208 = parser.ReadColumn< byte >( 208 );
            Unknown209 = parser.ReadColumn< byte >( 209 );
            Unknown210 = parser.ReadColumn< byte >( 210 );
            Unknown211 = parser.ReadColumn< byte >( 211 );
            Unknown212 = parser.ReadColumn< byte >( 212 );
            Unknown213 = parser.ReadColumn< byte >( 213 );
            Unknown214 = parser.ReadColumn< byte >( 214 );
            Unknown215 = parser.ReadColumn< byte >( 215 );
            Unknown216 = parser.ReadColumn< byte >( 216 );
            Unknown217 = parser.ReadColumn< byte >( 217 );
            Unknown218 = parser.ReadColumn< byte >( 218 );
            Unknown219 = parser.ReadColumn< byte >( 219 );
            Unknown220 = parser.ReadColumn< byte >( 220 );
            Unknown221 = parser.ReadColumn< byte >( 221 );
            Unknown222 = parser.ReadColumn< byte >( 222 );
            Unknown223 = parser.ReadColumn< byte >( 223 );
            Unknown224 = parser.ReadColumn< byte >( 224 );
            Unknown225 = parser.ReadColumn< byte >( 225 );
            Unknown226 = parser.ReadColumn< byte >( 226 );
            Unknown227 = parser.ReadColumn< byte >( 227 );
            Unknown228 = parser.ReadColumn< byte >( 228 );
            Unknown229 = parser.ReadColumn< byte >( 229 );
            Unknown230 = parser.ReadColumn< byte >( 230 );
            Unknown231 = parser.ReadColumn< byte >( 231 );
            Unknown232 = parser.ReadColumn< byte >( 232 );
            Unknown233 = parser.ReadColumn< byte >( 233 );
            Unknown234 = parser.ReadColumn< byte >( 234 );
            Unknown235 = parser.ReadColumn< byte >( 235 );
            Unknown236 = parser.ReadColumn< byte >( 236 );
            Unknown237 = parser.ReadColumn< byte >( 237 );
            Unknown238 = parser.ReadColumn< byte >( 238 );
            Unknown239 = parser.ReadColumn< byte >( 239 );
            Unknown240 = parser.ReadColumn< byte >( 240 );
            Unknown241 = parser.ReadColumn< byte >( 241 );
            Unknown242 = parser.ReadColumn< byte >( 242 );
            Unknown243 = parser.ReadColumn< byte >( 243 );
            Unknown244 = parser.ReadColumn< byte >( 244 );
            Unknown245 = parser.ReadColumn< byte >( 245 );
            Unknown246 = parser.ReadColumn< byte >( 246 );
            Unknown247 = parser.ReadColumn< byte >( 247 );
            Unknown248 = parser.ReadColumn< byte >( 248 );
            Unknown249 = parser.ReadColumn< byte >( 249 );
            Unknown250 = parser.ReadColumn< byte >( 250 );
            Unknown251 = parser.ReadColumn< byte >( 251 );
            Unknown252 = parser.ReadColumn< byte >( 252 );
            Unknown253 = parser.ReadColumn< byte >( 253 );
            Unknown254 = parser.ReadColumn< byte >( 254 );
            Unknown255 = parser.ReadColumn< byte >( 255 );
            Unknown256 = parser.ReadColumn< byte >( 256 );
            Unknown257 = parser.ReadColumn< byte >( 257 );
            Unknown258 = parser.ReadColumn< byte >( 258 );
            Unknown259 = parser.ReadColumn< byte >( 259 );
            Unknown260 = parser.ReadColumn< byte >( 260 );
            Unknown261 = parser.ReadColumn< byte >( 261 );
            Unknown262 = parser.ReadColumn< byte >( 262 );
            Unknown263 = parser.ReadColumn< byte >( 263 );
            Unknown264 = parser.ReadColumn< byte >( 264 );
            Unknown265 = parser.ReadColumn< byte >( 265 );
            Unknown266 = parser.ReadColumn< byte >( 266 );
            Unknown267 = parser.ReadColumn< byte >( 267 );
            Unknown268 = parser.ReadColumn< byte >( 268 );
            Unknown269 = parser.ReadColumn< byte >( 269 );
            Unknown270 = parser.ReadColumn< byte >( 270 );
            Unknown271 = parser.ReadColumn< byte >( 271 );
            Unknown272 = parser.ReadColumn< byte >( 272 );
            Unknown273 = parser.ReadColumn< int >( 273 );
            Unknown274 = parser.ReadColumn< int >( 274 );
            Unknown275 = parser.ReadColumn< int >( 275 );
            Unknown276 = parser.ReadColumn< int >( 276 );
            Unknown277 = parser.ReadColumn< int >( 277 );
            Unknown278 = parser.ReadColumn< int >( 278 );
            Unknown279 = parser.ReadColumn< int >( 279 );
            Unknown280 = parser.ReadColumn< int >( 280 );
            Unknown281 = parser.ReadColumn< int >( 281 );
            Unknown282 = parser.ReadColumn< int >( 282 );
            Unknown283 = parser.ReadColumn< int >( 283 );
            Unknown284 = parser.ReadColumn< int >( 284 );
            Unknown285 = parser.ReadColumn< int >( 285 );
            Unknown286 = parser.ReadColumn< int >( 286 );
            Unknown287 = parser.ReadColumn< int >( 287 );
            Unknown288 = parser.ReadColumn< int >( 288 );
            Unknown289 = parser.ReadColumn< int >( 289 );
            Unknown290 = parser.ReadColumn< int >( 290 );
            Unknown291 = parser.ReadColumn< int >( 291 );
            Unknown292 = parser.ReadColumn< int >( 292 );
            Unknown293 = parser.ReadColumn< int >( 293 );
            Unknown294 = parser.ReadColumn< int >( 294 );
            Unknown295 = parser.ReadColumn< int >( 295 );
            Unknown296 = parser.ReadColumn< int >( 296 );
            Unknown297 = parser.ReadColumn< int >( 297 );
            Unknown298 = parser.ReadColumn< int >( 298 );
            Unknown299 = parser.ReadColumn< int >( 299 );
            Unknown300 = parser.ReadColumn< int >( 300 );
            Unknown301 = parser.ReadColumn< int >( 301 );
            Unknown302 = parser.ReadColumn< int >( 302 );
            Unknown303 = parser.ReadColumn< int >( 303 );
            Unknown304 = parser.ReadColumn< int >( 304 );
            Unknown305 = parser.ReadColumn< int >( 305 );
            Unknown306 = parser.ReadColumn< int >( 306 );
            Unknown307 = parser.ReadColumn< int >( 307 );
            Unknown308 = parser.ReadColumn< int >( 308 );
            Unknown309 = parser.ReadColumn< int >( 309 );
            Unknown310 = parser.ReadColumn< int >( 310 );
            Unknown311 = parser.ReadColumn< int >( 311 );
            Unknown312 = parser.ReadColumn< int >( 312 );
            Unknown313 = parser.ReadColumn< int >( 313 );
            Unknown314 = parser.ReadColumn< int >( 314 );
            Unknown315 = parser.ReadColumn< int >( 315 );
            Unknown316 = parser.ReadColumn< int >( 316 );
            Unknown317 = parser.ReadColumn< int >( 317 );
            Unknown318 = parser.ReadColumn< int >( 318 );
            Unknown319 = parser.ReadColumn< int >( 319 );
            Unknown320 = parser.ReadColumn< int >( 320 );
            Unknown321 = parser.ReadColumn< int >( 321 );
            Unknown322 = parser.ReadColumn< int >( 322 );
            Unknown323 = parser.ReadColumn< int >( 323 );
            Unknown324 = parser.ReadColumn< int >( 324 );
            Unknown325 = parser.ReadColumn< int >( 325 );
            Unknown326 = parser.ReadColumn< int >( 326 );
            Unknown327 = parser.ReadColumn< int >( 327 );
            Unknown328 = parser.ReadColumn< int >( 328 );
            Unknown329 = parser.ReadColumn< int >( 329 );
            Unknown330 = parser.ReadColumn< int >( 330 );
            Unknown331 = parser.ReadColumn< int >( 331 );
            Unknown332 = parser.ReadColumn< int >( 332 );
            Unknown333 = parser.ReadColumn< int >( 333 );
            Unknown334 = parser.ReadColumn< int >( 334 );
            Unknown335 = parser.ReadColumn< int >( 335 );
            Unknown336 = parser.ReadColumn< int >( 336 );
            Unknown337 = parser.ReadColumn< int >( 337 );
            Unknown338 = parser.ReadColumn< int >( 338 );
            Unknown339 = parser.ReadColumn< int >( 339 );
            Unknown340 = parser.ReadColumn< int >( 340 );
            Unknown341 = parser.ReadColumn< int >( 341 );
            Unknown342 = parser.ReadColumn< int >( 342 );
            Unknown343 = parser.ReadColumn< int >( 343 );
            Unknown344 = parser.ReadColumn< int >( 344 );
            Unknown345 = parser.ReadColumn< int >( 345 );
            Unknown346 = parser.ReadColumn< int >( 346 );
            Unknown347 = parser.ReadColumn< int >( 347 );
            Unknown348 = parser.ReadColumn< int >( 348 );
            Unknown349 = parser.ReadColumn< int >( 349 );
            Unknown350 = parser.ReadColumn< int >( 350 );
            Unknown351 = parser.ReadColumn< int >( 351 );
            Unknown352 = parser.ReadColumn< int >( 352 );
            Unknown353 = parser.ReadColumn< int >( 353 );
            Unknown354 = parser.ReadColumn< int >( 354 );
            Unknown355 = parser.ReadColumn< int >( 355 );
            Unknown356 = parser.ReadColumn< int >( 356 );
            Unknown357 = parser.ReadColumn< int >( 357 );
            Unknown358 = parser.ReadColumn< int >( 358 );
            Unknown359 = parser.ReadColumn< int >( 359 );
            Unknown360 = parser.ReadColumn< int >( 360 );
            Unknown361 = parser.ReadColumn< int >( 361 );
            Unknown362 = parser.ReadColumn< int >( 362 );
            Unknown363 = parser.ReadColumn< int >( 363 );
            Unknown364 = parser.ReadColumn< int >( 364 );
            Unknown365 = parser.ReadColumn< int >( 365 );
            Unknown366 = parser.ReadColumn< int >( 366 );
            Unknown367 = parser.ReadColumn< int >( 367 );
            Unknown368 = parser.ReadColumn< int >( 368 );
        }
    }
}