// ReSharper disable All

using Lumina.Text;
using Lumina.Data;
using Lumina.Data.Structs.Excel;

namespace Lumina.Excel.GeneratedSheets
{
    [Sheet( "PvPSeries", columnHash: 0x45504238 )]
    public partial class PvPSeries : ExcelRow
    {
        
        public byte Unknown0 { get; set; }
        public int[] LevelRewardItem { get; set; }
        public int Unknown3 { get; set; }
        public int Unknown4 { get; set; }
        public int Unknown5 { get; set; }
        public int Unknown6 { get; set; }
        public int Unknown7 { get; set; }
        public int Unknown8 { get; set; }
        public int Unknown9 { get; set; }
        public int Unknown10 { get; set; }
        public int Unknown11 { get; set; }
        public int Unknown12 { get; set; }
        public int Unknown13 { get; set; }
        public int Unknown14 { get; set; }
        public int Unknown15 { get; set; }
        public int Unknown16 { get; set; }
        public int Unknown17 { get; set; }
        public int Unknown18 { get; set; }
        public int Unknown19 { get; set; }
        public int Unknown20 { get; set; }
        public int Unknown21 { get; set; }
        public int Unknown22 { get; set; }
        public int Unknown23 { get; set; }
        public int Unknown24 { get; set; }
        public int Unknown25 { get; set; }
        public int Unknown26 { get; set; }
        public int Unknown27 { get; set; }
        public int Unknown28 { get; set; }
        public int Unknown29 { get; set; }
        public int Unknown30 { get; set; }
        public int Unknown31 { get; set; }
        public int Unknown32 { get; set; }
        public int Unknown33 { get; set; }
        public int Unknown34 { get; set; }
        public int Unknown35 { get; set; }
        public int Unknown36 { get; set; }
        public int Unknown37 { get; set; }
        public int Unknown38 { get; set; }
        public int Unknown39 { get; set; }
        public int Unknown40 { get; set; }
        public int Unknown41 { get; set; }
        public int Unknown42 { get; set; }
        public int Unknown43 { get; set; }
        public int Unknown44 { get; set; }
        public int Unknown45 { get; set; }
        public int Unknown46 { get; set; }
        public int Unknown47 { get; set; }
        public int Unknown48 { get; set; }
        public int Unknown49 { get; set; }
        public int Unknown50 { get; set; }
        public int Unknown51 { get; set; }
        public int Unknown52 { get; set; }
        public int Unknown53 { get; set; }
        public int Unknown54 { get; set; }
        public int Unknown55 { get; set; }
        public int Unknown56 { get; set; }
        public int Unknown57 { get; set; }
        public int Unknown58 { get; set; }
        public int Unknown59 { get; set; }
        public int Unknown60 { get; set; }
        public int Unknown61 { get; set; }
        public int Unknown62 { get; set; }
        public int Unknown63 { get; set; }
        public int Unknown64 { get; set; }
        public ushort[] LevelRewardCount { get; set; }
        public ushort Unknown67 { get; set; }
        public ushort Unknown68 { get; set; }
        public ushort Unknown69 { get; set; }
        public ushort Unknown70 { get; set; }
        public ushort Unknown71 { get; set; }
        public ushort Unknown72 { get; set; }
        public ushort Unknown73 { get; set; }
        public ushort Unknown74 { get; set; }
        public ushort Unknown75 { get; set; }
        public ushort Unknown76 { get; set; }
        public ushort Unknown77 { get; set; }
        public ushort Unknown78 { get; set; }
        public ushort Unknown79 { get; set; }
        public ushort Unknown80 { get; set; }
        public ushort Unknown81 { get; set; }
        public ushort Unknown82 { get; set; }
        public ushort Unknown83 { get; set; }
        public ushort Unknown84 { get; set; }
        public ushort Unknown85 { get; set; }
        public ushort Unknown86 { get; set; }
        public ushort Unknown87 { get; set; }
        public ushort Unknown88 { get; set; }
        public ushort Unknown89 { get; set; }
        public ushort Unknown90 { get; set; }
        public ushort Unknown91 { get; set; }
        public ushort Unknown92 { get; set; }
        public ushort Unknown93 { get; set; }
        public ushort Unknown94 { get; set; }
        public ushort Unknown95 { get; set; }
        public ushort Unknown96 { get; set; }
        public ushort Unknown97 { get; set; }
        public ushort Unknown98 { get; set; }
        public ushort Unknown99 { get; set; }
        public ushort Unknown100 { get; set; }
        public ushort Unknown101 { get; set; }
        public ushort Unknown102 { get; set; }
        public ushort Unknown103 { get; set; }
        public ushort Unknown104 { get; set; }
        public ushort Unknown105 { get; set; }
        public ushort Unknown106 { get; set; }
        public ushort Unknown107 { get; set; }
        public ushort Unknown108 { get; set; }
        public ushort Unknown109 { get; set; }
        public ushort Unknown110 { get; set; }
        public ushort Unknown111 { get; set; }
        public ushort Unknown112 { get; set; }
        public ushort Unknown113 { get; set; }
        public ushort Unknown114 { get; set; }
        public ushort Unknown115 { get; set; }
        public ushort Unknown116 { get; set; }
        public ushort Unknown117 { get; set; }
        public ushort Unknown118 { get; set; }
        public ushort Unknown119 { get; set; }
        public ushort Unknown120 { get; set; }
        public ushort Unknown121 { get; set; }
        public ushort Unknown122 { get; set; }
        public ushort Unknown123 { get; set; }
        public ushort Unknown124 { get; set; }
        public ushort Unknown125 { get; set; }
        public ushort Unknown126 { get; set; }
        public ushort Unknown127 { get; set; }
        public ushort Unknown128 { get; set; }
        public int Unknown129 { get; set; }
        public int Unknown130 { get; set; }
        public int Unknown131 { get; set; }
        public int Unknown132 { get; set; }
        public int Unknown133 { get; set; }
        public int Unknown134 { get; set; }
        public int Unknown135 { get; set; }
        public int Unknown136 { get; set; }
        public int Unknown137 { get; set; }
        public int Unknown138 { get; set; }
        public int Unknown139 { get; set; }
        public int Unknown140 { get; set; }
        public int Unknown141 { get; set; }
        public int Unknown142 { get; set; }
        public int Unknown143 { get; set; }
        public int Unknown144 { get; set; }
        public int Unknown145 { get; set; }
        public int Unknown146 { get; set; }
        public int Unknown147 { get; set; }
        public int Unknown148 { get; set; }
        public int Unknown149 { get; set; }
        public int Unknown150 { get; set; }
        public int Unknown151 { get; set; }
        public int Unknown152 { get; set; }
        public int Unknown153 { get; set; }
        public int Unknown154 { get; set; }
        public int Unknown155 { get; set; }
        public int Unknown156 { get; set; }
        public int Unknown157 { get; set; }
        public int Unknown158 { get; set; }
        public int Unknown159 { get; set; }
        public int Unknown160 { get; set; }
        
        public override void PopulateData( RowParser parser, GameData gameData, Language language )
        {
            base.PopulateData( parser, gameData, language );

            Unknown0 = parser.ReadColumn< byte >( 0 );
            LevelRewardItem = new int[ 2 ];
            for( var i = 0; i < 2; i++ )
                LevelRewardItem[ i ] = parser.ReadColumn< int >( 1 + i );
            Unknown3 = parser.ReadColumn< int >( 3 );
            Unknown4 = parser.ReadColumn< int >( 4 );
            Unknown5 = parser.ReadColumn< int >( 5 );
            Unknown6 = parser.ReadColumn< int >( 6 );
            Unknown7 = parser.ReadColumn< int >( 7 );
            Unknown8 = parser.ReadColumn< int >( 8 );
            Unknown9 = parser.ReadColumn< int >( 9 );
            Unknown10 = parser.ReadColumn< int >( 10 );
            Unknown11 = parser.ReadColumn< int >( 11 );
            Unknown12 = parser.ReadColumn< int >( 12 );
            Unknown13 = parser.ReadColumn< int >( 13 );
            Unknown14 = parser.ReadColumn< int >( 14 );
            Unknown15 = parser.ReadColumn< int >( 15 );
            Unknown16 = parser.ReadColumn< int >( 16 );
            Unknown17 = parser.ReadColumn< int >( 17 );
            Unknown18 = parser.ReadColumn< int >( 18 );
            Unknown19 = parser.ReadColumn< int >( 19 );
            Unknown20 = parser.ReadColumn< int >( 20 );
            Unknown21 = parser.ReadColumn< int >( 21 );
            Unknown22 = parser.ReadColumn< int >( 22 );
            Unknown23 = parser.ReadColumn< int >( 23 );
            Unknown24 = parser.ReadColumn< int >( 24 );
            Unknown25 = parser.ReadColumn< int >( 25 );
            Unknown26 = parser.ReadColumn< int >( 26 );
            Unknown27 = parser.ReadColumn< int >( 27 );
            Unknown28 = parser.ReadColumn< int >( 28 );
            Unknown29 = parser.ReadColumn< int >( 29 );
            Unknown30 = parser.ReadColumn< int >( 30 );
            Unknown31 = parser.ReadColumn< int >( 31 );
            Unknown32 = parser.ReadColumn< int >( 32 );
            Unknown33 = parser.ReadColumn< int >( 33 );
            Unknown34 = parser.ReadColumn< int >( 34 );
            Unknown35 = parser.ReadColumn< int >( 35 );
            Unknown36 = parser.ReadColumn< int >( 36 );
            Unknown37 = parser.ReadColumn< int >( 37 );
            Unknown38 = parser.ReadColumn< int >( 38 );
            Unknown39 = parser.ReadColumn< int >( 39 );
            Unknown40 = parser.ReadColumn< int >( 40 );
            Unknown41 = parser.ReadColumn< int >( 41 );
            Unknown42 = parser.ReadColumn< int >( 42 );
            Unknown43 = parser.ReadColumn< int >( 43 );
            Unknown44 = parser.ReadColumn< int >( 44 );
            Unknown45 = parser.ReadColumn< int >( 45 );
            Unknown46 = parser.ReadColumn< int >( 46 );
            Unknown47 = parser.ReadColumn< int >( 47 );
            Unknown48 = parser.ReadColumn< int >( 48 );
            Unknown49 = parser.ReadColumn< int >( 49 );
            Unknown50 = parser.ReadColumn< int >( 50 );
            Unknown51 = parser.ReadColumn< int >( 51 );
            Unknown52 = parser.ReadColumn< int >( 52 );
            Unknown53 = parser.ReadColumn< int >( 53 );
            Unknown54 = parser.ReadColumn< int >( 54 );
            Unknown55 = parser.ReadColumn< int >( 55 );
            Unknown56 = parser.ReadColumn< int >( 56 );
            Unknown57 = parser.ReadColumn< int >( 57 );
            Unknown58 = parser.ReadColumn< int >( 58 );
            Unknown59 = parser.ReadColumn< int >( 59 );
            Unknown60 = parser.ReadColumn< int >( 60 );
            Unknown61 = parser.ReadColumn< int >( 61 );
            Unknown62 = parser.ReadColumn< int >( 62 );
            Unknown63 = parser.ReadColumn< int >( 63 );
            Unknown64 = parser.ReadColumn< int >( 64 );
            LevelRewardCount = new ushort[ 2 ];
            for( var i = 0; i < 2; i++ )
                LevelRewardCount[ i ] = parser.ReadColumn< ushort >( 65 + i );
            Unknown67 = parser.ReadColumn< ushort >( 67 );
            Unknown68 = parser.ReadColumn< ushort >( 68 );
            Unknown69 = parser.ReadColumn< ushort >( 69 );
            Unknown70 = parser.ReadColumn< ushort >( 70 );
            Unknown71 = parser.ReadColumn< ushort >( 71 );
            Unknown72 = parser.ReadColumn< ushort >( 72 );
            Unknown73 = parser.ReadColumn< ushort >( 73 );
            Unknown74 = parser.ReadColumn< ushort >( 74 );
            Unknown75 = parser.ReadColumn< ushort >( 75 );
            Unknown76 = parser.ReadColumn< ushort >( 76 );
            Unknown77 = parser.ReadColumn< ushort >( 77 );
            Unknown78 = parser.ReadColumn< ushort >( 78 );
            Unknown79 = parser.ReadColumn< ushort >( 79 );
            Unknown80 = parser.ReadColumn< ushort >( 80 );
            Unknown81 = parser.ReadColumn< ushort >( 81 );
            Unknown82 = parser.ReadColumn< ushort >( 82 );
            Unknown83 = parser.ReadColumn< ushort >( 83 );
            Unknown84 = parser.ReadColumn< ushort >( 84 );
            Unknown85 = parser.ReadColumn< ushort >( 85 );
            Unknown86 = parser.ReadColumn< ushort >( 86 );
            Unknown87 = parser.ReadColumn< ushort >( 87 );
            Unknown88 = parser.ReadColumn< ushort >( 88 );
            Unknown89 = parser.ReadColumn< ushort >( 89 );
            Unknown90 = parser.ReadColumn< ushort >( 90 );
            Unknown91 = parser.ReadColumn< ushort >( 91 );
            Unknown92 = parser.ReadColumn< ushort >( 92 );
            Unknown93 = parser.ReadColumn< ushort >( 93 );
            Unknown94 = parser.ReadColumn< ushort >( 94 );
            Unknown95 = parser.ReadColumn< ushort >( 95 );
            Unknown96 = parser.ReadColumn< ushort >( 96 );
            Unknown97 = parser.ReadColumn< ushort >( 97 );
            Unknown98 = parser.ReadColumn< ushort >( 98 );
            Unknown99 = parser.ReadColumn< ushort >( 99 );
            Unknown100 = parser.ReadColumn< ushort >( 100 );
            Unknown101 = parser.ReadColumn< ushort >( 101 );
            Unknown102 = parser.ReadColumn< ushort >( 102 );
            Unknown103 = parser.ReadColumn< ushort >( 103 );
            Unknown104 = parser.ReadColumn< ushort >( 104 );
            Unknown105 = parser.ReadColumn< ushort >( 105 );
            Unknown106 = parser.ReadColumn< ushort >( 106 );
            Unknown107 = parser.ReadColumn< ushort >( 107 );
            Unknown108 = parser.ReadColumn< ushort >( 108 );
            Unknown109 = parser.ReadColumn< ushort >( 109 );
            Unknown110 = parser.ReadColumn< ushort >( 110 );
            Unknown111 = parser.ReadColumn< ushort >( 111 );
            Unknown112 = parser.ReadColumn< ushort >( 112 );
            Unknown113 = parser.ReadColumn< ushort >( 113 );
            Unknown114 = parser.ReadColumn< ushort >( 114 );
            Unknown115 = parser.ReadColumn< ushort >( 115 );
            Unknown116 = parser.ReadColumn< ushort >( 116 );
            Unknown117 = parser.ReadColumn< ushort >( 117 );
            Unknown118 = parser.ReadColumn< ushort >( 118 );
            Unknown119 = parser.ReadColumn< ushort >( 119 );
            Unknown120 = parser.ReadColumn< ushort >( 120 );
            Unknown121 = parser.ReadColumn< ushort >( 121 );
            Unknown122 = parser.ReadColumn< ushort >( 122 );
            Unknown123 = parser.ReadColumn< ushort >( 123 );
            Unknown124 = parser.ReadColumn< ushort >( 124 );
            Unknown125 = parser.ReadColumn< ushort >( 125 );
            Unknown126 = parser.ReadColumn< ushort >( 126 );
            Unknown127 = parser.ReadColumn< ushort >( 127 );
            Unknown128 = parser.ReadColumn< ushort >( 128 );
            Unknown129 = parser.ReadColumn< int >( 129 );
            Unknown130 = parser.ReadColumn< int >( 130 );
            Unknown131 = parser.ReadColumn< int >( 131 );
            Unknown132 = parser.ReadColumn< int >( 132 );
            Unknown133 = parser.ReadColumn< int >( 133 );
            Unknown134 = parser.ReadColumn< int >( 134 );
            Unknown135 = parser.ReadColumn< int >( 135 );
            Unknown136 = parser.ReadColumn< int >( 136 );
            Unknown137 = parser.ReadColumn< int >( 137 );
            Unknown138 = parser.ReadColumn< int >( 138 );
            Unknown139 = parser.ReadColumn< int >( 139 );
            Unknown140 = parser.ReadColumn< int >( 140 );
            Unknown141 = parser.ReadColumn< int >( 141 );
            Unknown142 = parser.ReadColumn< int >( 142 );
            Unknown143 = parser.ReadColumn< int >( 143 );
            Unknown144 = parser.ReadColumn< int >( 144 );
            Unknown145 = parser.ReadColumn< int >( 145 );
            Unknown146 = parser.ReadColumn< int >( 146 );
            Unknown147 = parser.ReadColumn< int >( 147 );
            Unknown148 = parser.ReadColumn< int >( 148 );
            Unknown149 = parser.ReadColumn< int >( 149 );
            Unknown150 = parser.ReadColumn< int >( 150 );
            Unknown151 = parser.ReadColumn< int >( 151 );
            Unknown152 = parser.ReadColumn< int >( 152 );
            Unknown153 = parser.ReadColumn< int >( 153 );
            Unknown154 = parser.ReadColumn< int >( 154 );
            Unknown155 = parser.ReadColumn< int >( 155 );
            Unknown156 = parser.ReadColumn< int >( 156 );
            Unknown157 = parser.ReadColumn< int >( 157 );
            Unknown158 = parser.ReadColumn< int >( 158 );
            Unknown159 = parser.ReadColumn< int >( 159 );
            Unknown160 = parser.ReadColumn< int >( 160 );
        }
    }
}