// ReSharper disable All

using Lumina.Text;
using Lumina.Data;
using Lumina.Data.Structs.Excel;

namespace Lumina.Excel.GeneratedSheets
{
    [Sheet( "Quest", columnHash: 0xfc57448f )]
    public class Quest : IExcelRow
    {
        
        public SeString Name;
        public SeString Id;
        public LazyRow< ExVersion > Expansion;
        public LazyRow< ClassJobCategory > ClassJobCategory0;
        public ushort ClassJobLevel0;
        public byte QuestLevelOffset;
        public LazyRow< ClassJobCategory > ClassJobCategory1;
        public ushort ClassJobLevel1;
        public byte PreviousQuestJoin;
        public LazyRow< Quest > PreviousQuest0;
        public byte Unknown10;
        public LazyRow< Quest > PreviousQuest1;
        public LazyRow< Quest > PreviousQuest2;
        public byte QuestLockJoin;
        public LazyRow< Quest >[] QuestLock;
        public ushort Header;
        public byte Unknown17;
        public byte Unknown18;
        public LazyRow< ClassJob > ClassJobUnlock;
        public LazyRow< GrandCompany > GrandCompany;
        public LazyRow< GrandCompanyRank > GrandCompanyRank;
        public byte InstanceContentJoin;
        public LazyRow< InstanceContent >[] InstanceContent;
        public LazyRow< Festival > Festival;
        public byte FestivalBegin;
        public byte FestivalEnd;
        public ushort BellStart;
        public ushort BellEnd;
        public LazyRow< BeastTribe > BeastTribe;
        public LazyRow< BeastReputationRank > BeastReputationRank;
        public ushort BeastReputationValue;
        public byte Unknown34;
        public byte Unknown35;
        public LazyRow< Mount > MountRequired;
        public bool IsHouseRequired;
        public LazyRow< DeliveryQuest > DeliveryQuest;
        public uint IssuerStart;
        public LazyRow< Level > IssuerLocation;
        public LazyRow< Behavior > ClientBehavior;
        public uint TargetEnd;
        public bool IsRepeatable;
        public byte RepeatIntervalType;
        public LazyRow< QuestRepeatFlag > QuestRepeatFlag;
        public bool CanCancel;
        public byte Type;
        public LazyRow< QuestClassJobSupply > QuestClassJobSupply;
        public SeString[] ScriptInstruction;
        public uint[] ScriptArg;
        public byte[] ActorSpawnSeq;
        public byte[] ActorDespawnSeq;
        public uint[] Listener;
        public byte[] QuestUInt8A;
        public byte[] QuestUInt8B;
        public byte[] ConditionType;
        public uint[] ConditionValue;
        public byte[] ConditionOperator;
        public ushort[] Behavior;
        public bool[] VisibleBool;
        public bool[] ConditionBool;
        public bool[] ItemBool;
        public bool[] AnnounceBool;
        public bool[] BehaviorBool;
        public bool[] AcceptBool;
        public bool[] QualifiedBool;
        public bool[] CanTargetBool;
        public byte[] ToDoCompleteSeq;
        public byte[] ToDoQty;
        public LazyRow< Level >[] ToDoMainLocation;
        public uint[] Unknown1245;
        public uint Unknown1252;
        public uint Unknown1253;
        public uint Unknown1254;
        public uint Unknown1255;
        public uint Unknown1256;
        public uint Unknown1257;
        public uint Unknown1258;
        public uint Unknown1259;
        public uint Unknown1260;
        public uint Unknown1261;
        public uint Unknown1262;
        public uint Unknown1263;
        public uint Unknown1264;
        public uint Unknown1265;
        public uint Unknown1266;
        public uint Unknown1267;
        public uint Unknown1268;
        public uint Unknown1269;
        public uint Unknown1270;
        public uint Unknown1271;
        public uint Unknown1272;
        public uint Unknown1273;
        public uint Unknown1274;
        public uint Unknown1275;
        public uint Unknown1276;
        public uint Unknown1277;
        public uint Unknown1278;
        public uint Unknown1279;
        public uint Unknown1280;
        public uint Unknown1281;
        public uint Unknown1282;
        public uint Unknown1283;
        public uint Unknown1284;
        public uint Unknown1285;
        public uint Unknown1286;
        public uint Unknown1287;
        public uint Unknown1288;
        public uint Unknown1289;
        public uint Unknown1290;
        public uint Unknown1291;
        public uint Unknown1292;
        public uint Unknown1293;
        public uint Unknown1294;
        public uint Unknown1295;
        public uint Unknown1296;
        public uint Unknown1297;
        public uint Unknown1298;
        public uint Unknown1299;
        public uint Unknown1300;
        public uint Unknown1301;
        public uint Unknown1302;
        public uint Unknown1303;
        public uint Unknown1304;
        public uint Unknown1305;
        public uint Unknown1306;
        public uint Unknown1307;
        public uint Unknown1308;
        public uint Unknown1309;
        public uint Unknown1310;
        public uint Unknown1311;
        public uint Unknown1312;
        public uint Unknown1313;
        public uint Unknown1314;
        public uint Unknown1315;
        public uint Unknown1316;
        public uint Unknown1317;
        public uint Unknown1318;
        public uint Unknown1319;
        public uint Unknown1320;
        public uint Unknown1321;
        public uint Unknown1322;
        public uint Unknown1323;
        public uint Unknown1324;
        public uint Unknown1325;
        public uint Unknown1326;
        public uint Unknown1327;
        public uint Unknown1328;
        public uint Unknown1329;
        public uint Unknown1330;
        public uint Unknown1331;
        public uint Unknown1332;
        public uint Unknown1333;
        public uint Unknown1334;
        public uint Unknown1335;
        public uint Unknown1336;
        public uint Unknown1337;
        public uint Unknown1338;
        public uint Unknown1339;
        public uint Unknown1340;
        public uint Unknown1341;
        public uint Unknown1342;
        public uint Unknown1343;
        public uint Unknown1344;
        public uint Unknown1345;
        public uint Unknown1346;
        public uint Unknown1347;
        public uint Unknown1348;
        public uint Unknown1349;
        public uint Unknown1350;
        public uint Unknown1351;
        public uint Unknown1352;
        public uint Unknown1353;
        public uint Unknown1354;
        public uint Unknown1355;
        public uint Unknown1356;
        public uint Unknown1357;
        public uint Unknown1358;
        public uint Unknown1359;
        public uint Unknown1360;
        public uint Unknown1361;
        public uint Unknown1362;
        public uint Unknown1363;
        public uint Unknown1364;
        public uint Unknown1365;
        public uint Unknown1366;
        public uint Unknown1367;
        public uint Unknown1368;
        public uint Unknown1369;
        public uint Unknown1370;
        public uint Unknown1371;
        public uint Unknown1372;
        public uint Unknown1373;
        public uint Unknown1374;
        public uint Unknown1375;
        public uint Unknown1376;
        public uint Unknown1377;
        public uint Unknown1378;
        public uint Unknown1379;
        public uint Unknown1380;
        public uint Unknown1381;
        public uint Unknown1382;
        public uint Unknown1383;
        public uint Unknown1384;
        public uint Unknown1385;
        public uint Unknown1386;
        public uint Unknown1387;
        public uint Unknown1388;
        public uint Unknown1389;
        public uint Unknown1390;
        public uint Unknown1391;
        public uint Unknown1392;
        public uint Unknown1393;
        public uint Unknown1394;
        public uint Unknown1395;
        public uint Unknown1396;
        public uint Unknown1397;
        public uint Unknown1398;
        public uint Unknown1399;
        public uint Unknown1400;
        public uint Unknown1401;
        public uint Unknown1402;
        public uint Unknown1403;
        public uint Unknown1404;
        public uint Unknown1405;
        public uint Unknown1406;
        public uint Unknown1407;
        public uint Unknown1408;
        public uint Unknown1409;
        public uint Unknown1410;
        public uint Unknown1411;
        public uint Unknown1412;
        public byte[] CountableNum;
        public byte LevelMax;
        public LazyRow< ClassJob > ClassJobRequired;
        public byte Unknown1439;
        public ushort ExpFactor;
        public uint GilReward;
        public uint Unknown1442;
        public ushort GCSeals;
        public LazyRow< Item >[] ItemCatalyst;
        public byte[] ItemCountCatalyst;
        public byte ItemRewardType;
        public uint[] ItemReward0;
        public byte[] ItemCountReward0;
        public byte Unknown1464;
        public LazyRow< Stain >[] StainReward0;
        public byte Unknown1471;
        public LazyRow< Item >[] ItemReward1;
        public byte[] ItemCountReward1;
        public bool[] IsHQReward1;
        public LazyRow< Stain >[] StainReward1;
        public LazyRow< Emote > EmoteReward;
        public LazyRow< Action > ActionReward;
        public LazyRow< GeneralAction >[] GeneralActionReward;
        public LazyRow< Action > SystemReward0;
        public LazyRow< QuestRewardOther > OtherReward;
        public LazyRow< Action > SystemReward1;
        public LazyRow< Action > GCTypeReward;
        public LazyRow< InstanceContent > InstanceContentUnlock;
        public byte Unknown1501;
        public byte TomestoneReward;
        public byte TomestoneCountReward;
        public byte ReputationReward;
        public LazyRow< PlaceName > PlaceName;
        public LazyRow< JournalGenre > JournalGenre;
        public byte Unknown1507;
        public uint Icon;
        public uint IconSpecial;
        public bool Introduction;
        public bool HideOfferIcon;
        public LazyRow< EventIconType > EventIconType;
        public byte Unknown1513;
        public ushort SortKey;
        
        public uint RowId { get; set; }
        public uint SubRowId { get; set; }

        public void PopulateData( RowParser parser, Lumina lumina, Language language )
        {
            RowId = parser.Row;
            SubRowId = parser.SubRow;

            Name = parser.ReadColumn< SeString >( 0 );
            Id = parser.ReadColumn< SeString >( 1 );
            Expansion = new LazyRow< ExVersion >( lumina, parser.ReadColumn< byte >( 2 ), language );
            ClassJobCategory0 = new LazyRow< ClassJobCategory >( lumina, parser.ReadColumn< byte >( 3 ), language );
            ClassJobLevel0 = parser.ReadColumn< ushort >( 4 );
            QuestLevelOffset = parser.ReadColumn< byte >( 5 );
            ClassJobCategory1 = new LazyRow< ClassJobCategory >( lumina, parser.ReadColumn< byte >( 6 ), language );
            ClassJobLevel1 = parser.ReadColumn< ushort >( 7 );
            PreviousQuestJoin = parser.ReadColumn< byte >( 8 );
            PreviousQuest0 = new LazyRow< Quest >( lumina, parser.ReadColumn< uint >( 9 ), language );
            Unknown10 = parser.ReadColumn< byte >( 10 );
            PreviousQuest1 = new LazyRow< Quest >( lumina, parser.ReadColumn< uint >( 11 ), language );
            PreviousQuest2 = new LazyRow< Quest >( lumina, parser.ReadColumn< uint >( 12 ), language );
            QuestLockJoin = parser.ReadColumn< byte >( 13 );
            QuestLock = new LazyRow< Quest >[ 2 ];
            for( var i = 0; i < 2; i++ )
                QuestLock[ i ] = new LazyRow< Quest >( lumina, parser.ReadColumn< uint >( 14 + i ), language );
            Header = parser.ReadColumn< ushort >( 16 );
            Unknown17 = parser.ReadColumn< byte >( 17 );
            Unknown18 = parser.ReadColumn< byte >( 18 );
            ClassJobUnlock = new LazyRow< ClassJob >( lumina, parser.ReadColumn< byte >( 19 ), language );
            GrandCompany = new LazyRow< GrandCompany >( lumina, parser.ReadColumn< byte >( 20 ), language );
            GrandCompanyRank = new LazyRow< GrandCompanyRank >( lumina, parser.ReadColumn< byte >( 21 ), language );
            InstanceContentJoin = parser.ReadColumn< byte >( 22 );
            InstanceContent = new LazyRow< InstanceContent >[ 3 ];
            for( var i = 0; i < 3; i++ )
                InstanceContent[ i ] = new LazyRow< InstanceContent >( lumina, parser.ReadColumn< uint >( 23 + i ), language );
            Festival = new LazyRow< Festival >( lumina, parser.ReadColumn< byte >( 26 ), language );
            FestivalBegin = parser.ReadColumn< byte >( 27 );
            FestivalEnd = parser.ReadColumn< byte >( 28 );
            BellStart = parser.ReadColumn< ushort >( 29 );
            BellEnd = parser.ReadColumn< ushort >( 30 );
            BeastTribe = new LazyRow< BeastTribe >( lumina, parser.ReadColumn< byte >( 31 ), language );
            BeastReputationRank = new LazyRow< BeastReputationRank >( lumina, parser.ReadColumn< byte >( 32 ), language );
            BeastReputationValue = parser.ReadColumn< ushort >( 33 );
            Unknown34 = parser.ReadColumn< byte >( 34 );
            Unknown35 = parser.ReadColumn< byte >( 35 );
            MountRequired = new LazyRow< Mount >( lumina, parser.ReadColumn< int >( 36 ), language );
            IsHouseRequired = parser.ReadColumn< bool >( 37 );
            DeliveryQuest = new LazyRow< DeliveryQuest >( lumina, parser.ReadColumn< byte >( 38 ), language );
            IssuerStart = parser.ReadColumn< uint >( 39 );
            IssuerLocation = new LazyRow< Level >( lumina, parser.ReadColumn< uint >( 40 ), language );
            ClientBehavior = new LazyRow< Behavior >( lumina, parser.ReadColumn< ushort >( 41 ), language );
            TargetEnd = parser.ReadColumn< uint >( 42 );
            IsRepeatable = parser.ReadColumn< bool >( 43 );
            RepeatIntervalType = parser.ReadColumn< byte >( 44 );
            QuestRepeatFlag = new LazyRow< QuestRepeatFlag >( lumina, parser.ReadColumn< byte >( 45 ), language );
            CanCancel = parser.ReadColumn< bool >( 46 );
            Type = parser.ReadColumn< byte >( 47 );
            QuestClassJobSupply = new LazyRow< QuestClassJobSupply >( lumina, parser.ReadColumn< ushort >( 48 ), language );
            ScriptInstruction = new SeString[ 50 ];
            for( var i = 0; i < 50; i++ )
                ScriptInstruction[ i ] = parser.ReadColumn< SeString >( 49 + i );
            ScriptArg = new uint[ 50 ];
            for( var i = 0; i < 50; i++ )
                ScriptArg[ i ] = parser.ReadColumn< uint >( 99 + i );
            ActorSpawnSeq = new byte[ 64 ];
            for( var i = 0; i < 64; i++ )
                ActorSpawnSeq[ i ] = parser.ReadColumn< byte >( 149 + i );
            ActorDespawnSeq = new byte[ 64 ];
            for( var i = 0; i < 64; i++ )
                ActorDespawnSeq[ i ] = parser.ReadColumn< byte >( 213 + i );
            Listener = new uint[ 64 ];
            for( var i = 0; i < 64; i++ )
                Listener[ i ] = parser.ReadColumn< uint >( 277 + i );
            QuestUInt8A = new byte[ 32 ];
            for( var i = 0; i < 32; i++ )
                QuestUInt8A[ i ] = parser.ReadColumn< byte >( 341 + i );
            QuestUInt8B = new byte[ 32 ];
            for( var i = 0; i < 32; i++ )
                QuestUInt8B[ i ] = parser.ReadColumn< byte >( 373 + i );
            ConditionType = new byte[ 64 ];
            for( var i = 0; i < 64; i++ )
                ConditionType[ i ] = parser.ReadColumn< byte >( 405 + i );
            ConditionValue = new uint[ 64 ];
            for( var i = 0; i < 64; i++ )
                ConditionValue[ i ] = parser.ReadColumn< uint >( 469 + i );
            ConditionOperator = new byte[ 64 ];
            for( var i = 0; i < 64; i++ )
                ConditionOperator[ i ] = parser.ReadColumn< byte >( 533 + i );
            Behavior = new ushort[ 64 ];
            for( var i = 0; i < 64; i++ )
                Behavior[ i ] = parser.ReadColumn< ushort >( 597 + i );
            VisibleBool = new bool[ 64 ];
            for( var i = 0; i < 64; i++ )
                VisibleBool[ i ] = parser.ReadColumn< bool >( 661 + i );
            ConditionBool = new bool[ 64 ];
            for( var i = 0; i < 64; i++ )
                ConditionBool[ i ] = parser.ReadColumn< bool >( 725 + i );
            ItemBool = new bool[ 64 ];
            for( var i = 0; i < 64; i++ )
                ItemBool[ i ] = parser.ReadColumn< bool >( 789 + i );
            AnnounceBool = new bool[ 64 ];
            for( var i = 0; i < 64; i++ )
                AnnounceBool[ i ] = parser.ReadColumn< bool >( 853 + i );
            BehaviorBool = new bool[ 64 ];
            for( var i = 0; i < 64; i++ )
                BehaviorBool[ i ] = parser.ReadColumn< bool >( 917 + i );
            AcceptBool = new bool[ 64 ];
            for( var i = 0; i < 64; i++ )
                AcceptBool[ i ] = parser.ReadColumn< bool >( 981 + i );
            QualifiedBool = new bool[ 64 ];
            for( var i = 0; i < 64; i++ )
                QualifiedBool[ i ] = parser.ReadColumn< bool >( 1045 + i );
            CanTargetBool = new bool[ 64 ];
            for( var i = 0; i < 64; i++ )
                CanTargetBool[ i ] = parser.ReadColumn< bool >( 1109 + i );
            ToDoCompleteSeq = new byte[ 24 ];
            for( var i = 0; i < 24; i++ )
                ToDoCompleteSeq[ i ] = parser.ReadColumn< byte >( 1173 + i );
            ToDoQty = new byte[ 24 ];
            for( var i = 0; i < 24; i++ )
                ToDoQty[ i ] = parser.ReadColumn< byte >( 1197 + i );
            ToDoMainLocation = new LazyRow< Level >[ 24 ];
            for( var i = 0; i < 24; i++ )
                ToDoMainLocation[ i ] = new LazyRow< Level >( lumina, parser.ReadColumn< uint >( 1221 + i ), language );
            Unknown1245 = new uint[ 7 ];
            for( var i = 0; i < 7; i++ )
                Unknown1245[ i ] = parser.ReadColumn< uint >( 1245 + i );
            Unknown1252 = parser.ReadColumn< uint >( 1252 );
            Unknown1253 = parser.ReadColumn< uint >( 1253 );
            Unknown1254 = parser.ReadColumn< uint >( 1254 );
            Unknown1255 = parser.ReadColumn< uint >( 1255 );
            Unknown1256 = parser.ReadColumn< uint >( 1256 );
            Unknown1257 = parser.ReadColumn< uint >( 1257 );
            Unknown1258 = parser.ReadColumn< uint >( 1258 );
            Unknown1259 = parser.ReadColumn< uint >( 1259 );
            Unknown1260 = parser.ReadColumn< uint >( 1260 );
            Unknown1261 = parser.ReadColumn< uint >( 1261 );
            Unknown1262 = parser.ReadColumn< uint >( 1262 );
            Unknown1263 = parser.ReadColumn< uint >( 1263 );
            Unknown1264 = parser.ReadColumn< uint >( 1264 );
            Unknown1265 = parser.ReadColumn< uint >( 1265 );
            Unknown1266 = parser.ReadColumn< uint >( 1266 );
            Unknown1267 = parser.ReadColumn< uint >( 1267 );
            Unknown1268 = parser.ReadColumn< uint >( 1268 );
            Unknown1269 = parser.ReadColumn< uint >( 1269 );
            Unknown1270 = parser.ReadColumn< uint >( 1270 );
            Unknown1271 = parser.ReadColumn< uint >( 1271 );
            Unknown1272 = parser.ReadColumn< uint >( 1272 );
            Unknown1273 = parser.ReadColumn< uint >( 1273 );
            Unknown1274 = parser.ReadColumn< uint >( 1274 );
            Unknown1275 = parser.ReadColumn< uint >( 1275 );
            Unknown1276 = parser.ReadColumn< uint >( 1276 );
            Unknown1277 = parser.ReadColumn< uint >( 1277 );
            Unknown1278 = parser.ReadColumn< uint >( 1278 );
            Unknown1279 = parser.ReadColumn< uint >( 1279 );
            Unknown1280 = parser.ReadColumn< uint >( 1280 );
            Unknown1281 = parser.ReadColumn< uint >( 1281 );
            Unknown1282 = parser.ReadColumn< uint >( 1282 );
            Unknown1283 = parser.ReadColumn< uint >( 1283 );
            Unknown1284 = parser.ReadColumn< uint >( 1284 );
            Unknown1285 = parser.ReadColumn< uint >( 1285 );
            Unknown1286 = parser.ReadColumn< uint >( 1286 );
            Unknown1287 = parser.ReadColumn< uint >( 1287 );
            Unknown1288 = parser.ReadColumn< uint >( 1288 );
            Unknown1289 = parser.ReadColumn< uint >( 1289 );
            Unknown1290 = parser.ReadColumn< uint >( 1290 );
            Unknown1291 = parser.ReadColumn< uint >( 1291 );
            Unknown1292 = parser.ReadColumn< uint >( 1292 );
            Unknown1293 = parser.ReadColumn< uint >( 1293 );
            Unknown1294 = parser.ReadColumn< uint >( 1294 );
            Unknown1295 = parser.ReadColumn< uint >( 1295 );
            Unknown1296 = parser.ReadColumn< uint >( 1296 );
            Unknown1297 = parser.ReadColumn< uint >( 1297 );
            Unknown1298 = parser.ReadColumn< uint >( 1298 );
            Unknown1299 = parser.ReadColumn< uint >( 1299 );
            Unknown1300 = parser.ReadColumn< uint >( 1300 );
            Unknown1301 = parser.ReadColumn< uint >( 1301 );
            Unknown1302 = parser.ReadColumn< uint >( 1302 );
            Unknown1303 = parser.ReadColumn< uint >( 1303 );
            Unknown1304 = parser.ReadColumn< uint >( 1304 );
            Unknown1305 = parser.ReadColumn< uint >( 1305 );
            Unknown1306 = parser.ReadColumn< uint >( 1306 );
            Unknown1307 = parser.ReadColumn< uint >( 1307 );
            Unknown1308 = parser.ReadColumn< uint >( 1308 );
            Unknown1309 = parser.ReadColumn< uint >( 1309 );
            Unknown1310 = parser.ReadColumn< uint >( 1310 );
            Unknown1311 = parser.ReadColumn< uint >( 1311 );
            Unknown1312 = parser.ReadColumn< uint >( 1312 );
            Unknown1313 = parser.ReadColumn< uint >( 1313 );
            Unknown1314 = parser.ReadColumn< uint >( 1314 );
            Unknown1315 = parser.ReadColumn< uint >( 1315 );
            Unknown1316 = parser.ReadColumn< uint >( 1316 );
            Unknown1317 = parser.ReadColumn< uint >( 1317 );
            Unknown1318 = parser.ReadColumn< uint >( 1318 );
            Unknown1319 = parser.ReadColumn< uint >( 1319 );
            Unknown1320 = parser.ReadColumn< uint >( 1320 );
            Unknown1321 = parser.ReadColumn< uint >( 1321 );
            Unknown1322 = parser.ReadColumn< uint >( 1322 );
            Unknown1323 = parser.ReadColumn< uint >( 1323 );
            Unknown1324 = parser.ReadColumn< uint >( 1324 );
            Unknown1325 = parser.ReadColumn< uint >( 1325 );
            Unknown1326 = parser.ReadColumn< uint >( 1326 );
            Unknown1327 = parser.ReadColumn< uint >( 1327 );
            Unknown1328 = parser.ReadColumn< uint >( 1328 );
            Unknown1329 = parser.ReadColumn< uint >( 1329 );
            Unknown1330 = parser.ReadColumn< uint >( 1330 );
            Unknown1331 = parser.ReadColumn< uint >( 1331 );
            Unknown1332 = parser.ReadColumn< uint >( 1332 );
            Unknown1333 = parser.ReadColumn< uint >( 1333 );
            Unknown1334 = parser.ReadColumn< uint >( 1334 );
            Unknown1335 = parser.ReadColumn< uint >( 1335 );
            Unknown1336 = parser.ReadColumn< uint >( 1336 );
            Unknown1337 = parser.ReadColumn< uint >( 1337 );
            Unknown1338 = parser.ReadColumn< uint >( 1338 );
            Unknown1339 = parser.ReadColumn< uint >( 1339 );
            Unknown1340 = parser.ReadColumn< uint >( 1340 );
            Unknown1341 = parser.ReadColumn< uint >( 1341 );
            Unknown1342 = parser.ReadColumn< uint >( 1342 );
            Unknown1343 = parser.ReadColumn< uint >( 1343 );
            Unknown1344 = parser.ReadColumn< uint >( 1344 );
            Unknown1345 = parser.ReadColumn< uint >( 1345 );
            Unknown1346 = parser.ReadColumn< uint >( 1346 );
            Unknown1347 = parser.ReadColumn< uint >( 1347 );
            Unknown1348 = parser.ReadColumn< uint >( 1348 );
            Unknown1349 = parser.ReadColumn< uint >( 1349 );
            Unknown1350 = parser.ReadColumn< uint >( 1350 );
            Unknown1351 = parser.ReadColumn< uint >( 1351 );
            Unknown1352 = parser.ReadColumn< uint >( 1352 );
            Unknown1353 = parser.ReadColumn< uint >( 1353 );
            Unknown1354 = parser.ReadColumn< uint >( 1354 );
            Unknown1355 = parser.ReadColumn< uint >( 1355 );
            Unknown1356 = parser.ReadColumn< uint >( 1356 );
            Unknown1357 = parser.ReadColumn< uint >( 1357 );
            Unknown1358 = parser.ReadColumn< uint >( 1358 );
            Unknown1359 = parser.ReadColumn< uint >( 1359 );
            Unknown1360 = parser.ReadColumn< uint >( 1360 );
            Unknown1361 = parser.ReadColumn< uint >( 1361 );
            Unknown1362 = parser.ReadColumn< uint >( 1362 );
            Unknown1363 = parser.ReadColumn< uint >( 1363 );
            Unknown1364 = parser.ReadColumn< uint >( 1364 );
            Unknown1365 = parser.ReadColumn< uint >( 1365 );
            Unknown1366 = parser.ReadColumn< uint >( 1366 );
            Unknown1367 = parser.ReadColumn< uint >( 1367 );
            Unknown1368 = parser.ReadColumn< uint >( 1368 );
            Unknown1369 = parser.ReadColumn< uint >( 1369 );
            Unknown1370 = parser.ReadColumn< uint >( 1370 );
            Unknown1371 = parser.ReadColumn< uint >( 1371 );
            Unknown1372 = parser.ReadColumn< uint >( 1372 );
            Unknown1373 = parser.ReadColumn< uint >( 1373 );
            Unknown1374 = parser.ReadColumn< uint >( 1374 );
            Unknown1375 = parser.ReadColumn< uint >( 1375 );
            Unknown1376 = parser.ReadColumn< uint >( 1376 );
            Unknown1377 = parser.ReadColumn< uint >( 1377 );
            Unknown1378 = parser.ReadColumn< uint >( 1378 );
            Unknown1379 = parser.ReadColumn< uint >( 1379 );
            Unknown1380 = parser.ReadColumn< uint >( 1380 );
            Unknown1381 = parser.ReadColumn< uint >( 1381 );
            Unknown1382 = parser.ReadColumn< uint >( 1382 );
            Unknown1383 = parser.ReadColumn< uint >( 1383 );
            Unknown1384 = parser.ReadColumn< uint >( 1384 );
            Unknown1385 = parser.ReadColumn< uint >( 1385 );
            Unknown1386 = parser.ReadColumn< uint >( 1386 );
            Unknown1387 = parser.ReadColumn< uint >( 1387 );
            Unknown1388 = parser.ReadColumn< uint >( 1388 );
            Unknown1389 = parser.ReadColumn< uint >( 1389 );
            Unknown1390 = parser.ReadColumn< uint >( 1390 );
            Unknown1391 = parser.ReadColumn< uint >( 1391 );
            Unknown1392 = parser.ReadColumn< uint >( 1392 );
            Unknown1393 = parser.ReadColumn< uint >( 1393 );
            Unknown1394 = parser.ReadColumn< uint >( 1394 );
            Unknown1395 = parser.ReadColumn< uint >( 1395 );
            Unknown1396 = parser.ReadColumn< uint >( 1396 );
            Unknown1397 = parser.ReadColumn< uint >( 1397 );
            Unknown1398 = parser.ReadColumn< uint >( 1398 );
            Unknown1399 = parser.ReadColumn< uint >( 1399 );
            Unknown1400 = parser.ReadColumn< uint >( 1400 );
            Unknown1401 = parser.ReadColumn< uint >( 1401 );
            Unknown1402 = parser.ReadColumn< uint >( 1402 );
            Unknown1403 = parser.ReadColumn< uint >( 1403 );
            Unknown1404 = parser.ReadColumn< uint >( 1404 );
            Unknown1405 = parser.ReadColumn< uint >( 1405 );
            Unknown1406 = parser.ReadColumn< uint >( 1406 );
            Unknown1407 = parser.ReadColumn< uint >( 1407 );
            Unknown1408 = parser.ReadColumn< uint >( 1408 );
            Unknown1409 = parser.ReadColumn< uint >( 1409 );
            Unknown1410 = parser.ReadColumn< uint >( 1410 );
            Unknown1411 = parser.ReadColumn< uint >( 1411 );
            Unknown1412 = parser.ReadColumn< uint >( 1412 );
            CountableNum = new byte[ 24 ];
            for( var i = 0; i < 24; i++ )
                CountableNum[ i ] = parser.ReadColumn< byte >( 1413 + i );
            LevelMax = parser.ReadColumn< byte >( 1437 );
            ClassJobRequired = new LazyRow< ClassJob >( lumina, parser.ReadColumn< byte >( 1438 ), language );
            Unknown1439 = parser.ReadColumn< byte >( 1439 );
            ExpFactor = parser.ReadColumn< ushort >( 1440 );
            GilReward = parser.ReadColumn< uint >( 1441 );
            Unknown1442 = parser.ReadColumn< uint >( 1442 );
            GCSeals = parser.ReadColumn< ushort >( 1443 );
            ItemCatalyst = new LazyRow< Item >[ 3 ];
            for( var i = 0; i < 3; i++ )
                ItemCatalyst[ i ] = new LazyRow< Item >( lumina, parser.ReadColumn< byte >( 1444 + i ), language );
            ItemCountCatalyst = new byte[ 3 ];
            for( var i = 0; i < 3; i++ )
                ItemCountCatalyst[ i ] = parser.ReadColumn< byte >( 1447 + i );
            ItemRewardType = parser.ReadColumn< byte >( 1450 );
            ItemReward0 = new uint[ 7 ];
            for( var i = 0; i < 7; i++ )
                ItemReward0[ i ] = parser.ReadColumn< uint >( 1451 + i );
            ItemCountReward0 = new byte[ 6 ];
            for( var i = 0; i < 6; i++ )
                ItemCountReward0[ i ] = parser.ReadColumn< byte >( 1458 + i );
            Unknown1464 = parser.ReadColumn< byte >( 1464 );
            StainReward0 = new LazyRow< Stain >[ 6 ];
            for( var i = 0; i < 6; i++ )
                StainReward0[ i ] = new LazyRow< Stain >( lumina, parser.ReadColumn< byte >( 1465 + i ), language );
            Unknown1471 = parser.ReadColumn< byte >( 1471 );
            ItemReward1 = new LazyRow< Item >[ 5 ];
            for( var i = 0; i < 5; i++ )
                ItemReward1[ i ] = new LazyRow< Item >( lumina, parser.ReadColumn< uint >( 1472 + i ), language );
            ItemCountReward1 = new byte[ 5 ];
            for( var i = 0; i < 5; i++ )
                ItemCountReward1[ i ] = parser.ReadColumn< byte >( 1477 + i );
            IsHQReward1 = new bool[ 5 ];
            for( var i = 0; i < 5; i++ )
                IsHQReward1[ i ] = parser.ReadColumn< bool >( 1482 + i );
            StainReward1 = new LazyRow< Stain >[ 5 ];
            for( var i = 0; i < 5; i++ )
                StainReward1[ i ] = new LazyRow< Stain >( lumina, parser.ReadColumn< byte >( 1487 + i ), language );
            EmoteReward = new LazyRow< Emote >( lumina, parser.ReadColumn< byte >( 1492 ), language );
            ActionReward = new LazyRow< Action >( lumina, parser.ReadColumn< ushort >( 1493 ), language );
            GeneralActionReward = new LazyRow< GeneralAction >[ 2 ];
            for( var i = 0; i < 2; i++ )
                GeneralActionReward[ i ] = new LazyRow< GeneralAction >( lumina, parser.ReadColumn< byte >( 1494 + i ), language );
            SystemReward0 = new LazyRow< Action >( lumina, parser.ReadColumn< ushort >( 1496 ), language );
            OtherReward = new LazyRow< QuestRewardOther >( lumina, parser.ReadColumn< byte >( 1497 ), language );
            SystemReward1 = new LazyRow< Action >( lumina, parser.ReadColumn< ushort >( 1498 ), language );
            GCTypeReward = new LazyRow< Action >( lumina, parser.ReadColumn< ushort >( 1499 ), language );
            InstanceContentUnlock = new LazyRow< InstanceContent >( lumina, parser.ReadColumn< uint >( 1500 ), language );
            Unknown1501 = parser.ReadColumn< byte >( 1501 );
            TomestoneReward = parser.ReadColumn< byte >( 1502 );
            TomestoneCountReward = parser.ReadColumn< byte >( 1503 );
            ReputationReward = parser.ReadColumn< byte >( 1504 );
            PlaceName = new LazyRow< PlaceName >( lumina, parser.ReadColumn< ushort >( 1505 ), language );
            JournalGenre = new LazyRow< JournalGenre >( lumina, parser.ReadColumn< byte >( 1506 ), language );
            Unknown1507 = parser.ReadColumn< byte >( 1507 );
            Icon = parser.ReadColumn< uint >( 1508 );
            IconSpecial = parser.ReadColumn< uint >( 1509 );
            Introduction = parser.ReadColumn< bool >( 1510 );
            HideOfferIcon = parser.ReadColumn< bool >( 1511 );
            EventIconType = new LazyRow< EventIconType >( lumina, parser.ReadColumn< byte >( 1512 ), language );
            Unknown1513 = parser.ReadColumn< byte >( 1513 );
            SortKey = parser.ReadColumn< ushort >( 1514 );
        }
    }
}