// ReSharper disable All

using Lumina.Data;
using Lumina.Data.Structs.Excel;

namespace Lumina.Excel.GeneratedSheets
{
    [Sheet( "Frontline04", columnHash: 0xdb491bc6 )]
    public class Frontline04 : IExcelRow
    {
        
        public LazyRow< Level > Level1;
        public LazyRow< Level > Level2;
        public LazyRow< Level > Level3;
        public int Unknown3;
        public int Unknown4;
        public int Unknown5;
        public LazyRow< Level >[] UnknownLevel;
        public int Unknown33;
        public int Unknown34;
        public int Unknown35;
        public int Unknown36;
        public int Unknown37;
        public int Unknown38;
        public int Unknown39;
        public int Unknown40;
        public int Unknown41;
        public int Unknown42;
        public int Unknown43;
        public int Unknown44;
        public int Unknown45;
        public int Unknown46;
        public int Unknown47;
        public int Unknown48;
        public int Unknown49;
        public int Unknown50;
        public int Unknown51;
        public int Unknown52;
        public int Unknown53;
        public int Unknown54;
        public int Unknown55;
        public int Unknown56;
        public int Unknown57;
        public int Unknown58;
        public int Unknown59;
        public int Unknown60;
        public int Unknown61;
        public int Unknown62;
        public int Unknown63;
        public int Unknown64;
        public int Unknown65;
        public int Unknown66;
        public int Unknown67;
        public int Unknown68;
        public int Unknown69;
        public int Unknown70;
        public int Unknown71;
        public int Unknown72;
        public int Unknown73;
        public int Unknown74;
        public int Unknown75;
        public int Unknown76;
        public int Unknown77;
        public int Unknown78;
        public int Unknown79;
        public int Unknown80;
        public int Unknown81;
        public int Unknown82;
        public int Unknown83;
        public int Unknown84;
        public int Unknown85;
        public int Unknown86;
        public int Unknown87;
        public int Unknown88;
        public byte Unknown89;
        public byte Unknown90;
        public byte Unknown91;
        public byte Unknown92;
        public byte Unknown93;
        public byte Unknown94;
        public byte Unknown95;
        public byte Unknown96;
        public byte Unknown97;
        public byte Unknown98;
        public byte Unknown99;
        public byte Unknown100;
        public byte Unknown101;
        public byte Unknown102;
        public byte Unknown103;
        public byte Unknown104;
        public byte Unknown105;
        public byte Unknown106;
        public byte Unknown107;
        public byte Unknown108;
        public byte Unknown109;
        public byte Unknown110;
        public byte Unknown111;
        public byte Unknown112;
        public byte Unknown113;
        public byte Unknown114;
        public byte Unknown115;
        public byte Unknown116;
        public byte Unknown117;
        public byte Unknown118;
        public byte Unknown119;
        public byte Unknown120;
        public byte Unknown121;
        public byte Unknown122;
        public byte Unknown123;
        public byte Unknown124;
        public byte Unknown125;
        public byte Unknown126;
        public byte Unknown127;
        public byte Unknown128;
        public byte Unknown129;
        public byte Unknown130;
        public byte Unknown131;
        public byte Unknown132;
        public byte Unknown133;
        public byte Unknown134;
        public byte Unknown135;
        public byte Unknown136;
        public byte Unknown137;
        public byte Unknown138;
        public byte Unknown139;
        public byte Unknown140;
        public byte Unknown141;
        public byte Unknown142;
        public byte Unknown143;
        public byte Unknown144;
        public byte Unknown145;
        public byte Unknown146;
        public byte Unknown147;
        public byte Unknown148;
        public byte Unknown149;
        public byte Unknown150;
        public byte Unknown151;
        public byte Unknown152;
        public byte Unknown153;
        public byte Unknown154;
        public byte Unknown155;
        public byte Unknown156;
        public byte Unknown157;
        public byte Unknown158;
        public byte Unknown159;
        public byte Unknown160;
        public byte Unknown161;
        public byte Unknown162;
        public byte Unknown163;
        public byte Unknown164;
        public byte Unknown165;
        public byte Unknown166;
        public byte Unknown167;
        public byte Unknown168;
        public byte Unknown169;
        public byte Unknown170;
        public byte Unknown171;
        public byte Unknown172;
        public byte Unknown173;
        public byte Unknown174;
        public byte Unknown175;
        public byte Unknown176;
        public byte Unknown177;
        public byte Unknown178;
        public byte Unknown179;
        public byte Unknown180;
        public byte Unknown181;
        public byte Unknown182;
        public byte Unknown183;
        public byte Unknown184;
        public byte Unknown185;
        public byte Unknown186;
        public byte Unknown187;
        public byte Unknown188;
        public byte Unknown189;
        public byte Unknown190;
        public byte Unknown191;
        public byte Unknown192;
        public byte Unknown193;
        public byte Unknown194;
        public byte Unknown195;
        public byte Unknown196;
        public byte Unknown197;
        public byte Unknown198;
        public byte Unknown199;
        public byte Unknown200;
        public byte Unknown201;
        public byte Unknown202;
        public byte Unknown203;
        public byte Unknown204;
        public byte Unknown205;
        public byte Unknown206;
        public byte Unknown207;
        public byte Unknown208;
        public byte Unknown209;
        public byte Unknown210;
        public byte Unknown211;
        public byte Unknown212;
        public byte Unknown213;
        public byte Unknown214;
        public byte Unknown215;
        public byte Unknown216;
        public byte Unknown217;
        public byte Unknown218;
        public byte Unknown219;
        public byte Unknown220;
        public byte Unknown221;
        public byte Unknown222;
        public byte Unknown223;
        public byte Unknown224;
        public byte Unknown225;
        public byte Unknown226;
        public byte Unknown227;
        public byte Unknown228;
        public byte Unknown229;
        public byte Unknown230;
        public byte Unknown231;
        public byte Unknown232;
        public byte Unknown233;
        public byte Unknown234;
        public byte Unknown235;
        public byte Unknown236;
        public byte Unknown237;
        public byte Unknown238;
        public byte Unknown239;
        public byte Unknown240;
        public byte Unknown241;
        public byte Unknown242;
        public byte Unknown243;
        public byte Unknown244;
        public byte Unknown245;
        public byte Unknown246;
        public byte Unknown247;
        public byte Unknown248;
        public byte Unknown249;
        public byte Unknown250;
        public byte Unknown251;
        public byte Unknown252;
        public byte Unknown253;
        public byte Unknown254;
        public byte Unknown255;
        public byte Unknown256;
        public byte Unknown257;
        public byte Unknown258;
        public byte Unknown259;
        public byte Unknown260;
        public byte Unknown261;
        public byte Unknown262;
        public byte Unknown263;
        public byte Unknown264;
        public byte Unknown265;
        public byte Unknown266;
        public byte Unknown267;
        public byte Unknown268;
        public byte Unknown269;
        public byte Unknown270;
        public byte Unknown271;
        public byte Unknown272;
        public int Unknown273;
        public int Unknown274;
        public int Unknown275;
        public int Unknown276;
        public int Unknown277;
        public int Unknown278;
        public int Unknown279;
        public int Unknown280;
        public int Unknown281;
        public int Unknown282;
        public int Unknown283;
        public int Unknown284;
        public int Unknown285;
        public int Unknown286;
        public int Unknown287;
        public int Unknown288;
        public int Unknown289;
        public int Unknown290;
        public int Unknown291;
        public int Unknown292;
        public int Unknown293;
        public int Unknown294;
        public int Unknown295;
        public int Unknown296;
        public int Unknown297;
        public int Unknown298;
        public int Unknown299;
        public int Unknown300;
        public int Unknown301;
        public int Unknown302;
        public int Unknown303;
        public int Unknown304;
        public int Unknown305;
        public int Unknown306;
        public int Unknown307;
        public int Unknown308;
        public int Unknown309;
        public int Unknown310;
        public int Unknown311;
        public int Unknown312;
        public int Unknown313;
        public int Unknown314;
        public int Unknown315;
        public int Unknown316;
        public int Unknown317;
        public int Unknown318;
        public int Unknown319;
        public int Unknown320;
        public int Unknown321;
        public int Unknown322;
        public int Unknown323;
        public int Unknown324;
        public int Unknown325;
        public int Unknown326;
        public int Unknown327;
        public int Unknown328;
        public int Unknown329;
        public int Unknown330;
        public int Unknown331;
        public int Unknown332;
        public int Unknown333;
        public int Unknown334;
        public int Unknown335;
        public int Unknown336;
        public int Unknown337;
        public int Unknown338;
        public int Unknown339;
        public int Unknown340;
        public int Unknown341;
        public int Unknown342;
        public int Unknown343;
        public int Unknown344;
        public int Unknown345;
        public int Unknown346;
        public int Unknown347;
        public int Unknown348;
        public int Unknown349;
        public int Unknown350;
        public int Unknown351;
        public int Unknown352;
        public int Unknown353;
        public int Unknown354;
        public int Unknown355;
        public int Unknown356;
        public int Unknown357;
        public int Unknown358;
        public int Unknown359;
        public int Unknown360;
        public int Unknown361;
        public int Unknown362;
        public int Unknown363;
        public int Unknown364;
        public int Unknown365;
        public int Unknown366;
        public int Unknown367;
        public int Unknown368;
        
        public uint RowId { get; set; }
        public uint SubRowId { get; set; }

        public void PopulateData( RowParser parser, Lumina lumina, Language language )
        {
            RowId = parser.Row;
            SubRowId = parser.SubRow;

            Level1 = new LazyRow< Level >( lumina, parser.ReadColumn< int >( 0 ), language );
            Level2 = new LazyRow< Level >( lumina, parser.ReadColumn< int >( 1 ), language );
            Level3 = new LazyRow< Level >( lumina, parser.ReadColumn< int >( 2 ), language );
            Unknown3 = parser.ReadColumn< int >( 3 );
            Unknown4 = parser.ReadColumn< int >( 4 );
            Unknown5 = parser.ReadColumn< int >( 5 );
            UnknownLevel = new LazyRow< Level >[ 27 ];
            for( var i = 0; i < 27; i++ )
                UnknownLevel[ i ] = new LazyRow< Level >( lumina, parser.ReadColumn< int >( 6 + i ), language );
            Unknown33 = parser.ReadColumn< int >( 33 );
            Unknown34 = parser.ReadColumn< int >( 34 );
            Unknown35 = parser.ReadColumn< int >( 35 );
            Unknown36 = parser.ReadColumn< int >( 36 );
            Unknown37 = parser.ReadColumn< int >( 37 );
            Unknown38 = parser.ReadColumn< int >( 38 );
            Unknown39 = parser.ReadColumn< int >( 39 );
            Unknown40 = parser.ReadColumn< int >( 40 );
            Unknown41 = parser.ReadColumn< int >( 41 );
            Unknown42 = parser.ReadColumn< int >( 42 );
            Unknown43 = parser.ReadColumn< int >( 43 );
            Unknown44 = parser.ReadColumn< int >( 44 );
            Unknown45 = parser.ReadColumn< int >( 45 );
            Unknown46 = parser.ReadColumn< int >( 46 );
            Unknown47 = parser.ReadColumn< int >( 47 );
            Unknown48 = parser.ReadColumn< int >( 48 );
            Unknown49 = parser.ReadColumn< int >( 49 );
            Unknown50 = parser.ReadColumn< int >( 50 );
            Unknown51 = parser.ReadColumn< int >( 51 );
            Unknown52 = parser.ReadColumn< int >( 52 );
            Unknown53 = parser.ReadColumn< int >( 53 );
            Unknown54 = parser.ReadColumn< int >( 54 );
            Unknown55 = parser.ReadColumn< int >( 55 );
            Unknown56 = parser.ReadColumn< int >( 56 );
            Unknown57 = parser.ReadColumn< int >( 57 );
            Unknown58 = parser.ReadColumn< int >( 58 );
            Unknown59 = parser.ReadColumn< int >( 59 );
            Unknown60 = parser.ReadColumn< int >( 60 );
            Unknown61 = parser.ReadColumn< int >( 61 );
            Unknown62 = parser.ReadColumn< int >( 62 );
            Unknown63 = parser.ReadColumn< int >( 63 );
            Unknown64 = parser.ReadColumn< int >( 64 );
            Unknown65 = parser.ReadColumn< int >( 65 );
            Unknown66 = parser.ReadColumn< int >( 66 );
            Unknown67 = parser.ReadColumn< int >( 67 );
            Unknown68 = parser.ReadColumn< int >( 68 );
            Unknown69 = parser.ReadColumn< int >( 69 );
            Unknown70 = parser.ReadColumn< int >( 70 );
            Unknown71 = parser.ReadColumn< int >( 71 );
            Unknown72 = parser.ReadColumn< int >( 72 );
            Unknown73 = parser.ReadColumn< int >( 73 );
            Unknown74 = parser.ReadColumn< int >( 74 );
            Unknown75 = parser.ReadColumn< int >( 75 );
            Unknown76 = parser.ReadColumn< int >( 76 );
            Unknown77 = parser.ReadColumn< int >( 77 );
            Unknown78 = parser.ReadColumn< int >( 78 );
            Unknown79 = parser.ReadColumn< int >( 79 );
            Unknown80 = parser.ReadColumn< int >( 80 );
            Unknown81 = parser.ReadColumn< int >( 81 );
            Unknown82 = parser.ReadColumn< int >( 82 );
            Unknown83 = parser.ReadColumn< int >( 83 );
            Unknown84 = parser.ReadColumn< int >( 84 );
            Unknown85 = parser.ReadColumn< int >( 85 );
            Unknown86 = parser.ReadColumn< int >( 86 );
            Unknown87 = parser.ReadColumn< int >( 87 );
            Unknown88 = parser.ReadColumn< int >( 88 );
            Unknown89 = parser.ReadColumn< byte >( 89 );
            Unknown90 = parser.ReadColumn< byte >( 90 );
            Unknown91 = parser.ReadColumn< byte >( 91 );
            Unknown92 = parser.ReadColumn< byte >( 92 );
            Unknown93 = parser.ReadColumn< byte >( 93 );
            Unknown94 = parser.ReadColumn< byte >( 94 );
            Unknown95 = parser.ReadColumn< byte >( 95 );
            Unknown96 = parser.ReadColumn< byte >( 96 );
            Unknown97 = parser.ReadColumn< byte >( 97 );
            Unknown98 = parser.ReadColumn< byte >( 98 );
            Unknown99 = parser.ReadColumn< byte >( 99 );
            Unknown100 = parser.ReadColumn< byte >( 100 );
            Unknown101 = parser.ReadColumn< byte >( 101 );
            Unknown102 = parser.ReadColumn< byte >( 102 );
            Unknown103 = parser.ReadColumn< byte >( 103 );
            Unknown104 = parser.ReadColumn< byte >( 104 );
            Unknown105 = parser.ReadColumn< byte >( 105 );
            Unknown106 = parser.ReadColumn< byte >( 106 );
            Unknown107 = parser.ReadColumn< byte >( 107 );
            Unknown108 = parser.ReadColumn< byte >( 108 );
            Unknown109 = parser.ReadColumn< byte >( 109 );
            Unknown110 = parser.ReadColumn< byte >( 110 );
            Unknown111 = parser.ReadColumn< byte >( 111 );
            Unknown112 = parser.ReadColumn< byte >( 112 );
            Unknown113 = parser.ReadColumn< byte >( 113 );
            Unknown114 = parser.ReadColumn< byte >( 114 );
            Unknown115 = parser.ReadColumn< byte >( 115 );
            Unknown116 = parser.ReadColumn< byte >( 116 );
            Unknown117 = parser.ReadColumn< byte >( 117 );
            Unknown118 = parser.ReadColumn< byte >( 118 );
            Unknown119 = parser.ReadColumn< byte >( 119 );
            Unknown120 = parser.ReadColumn< byte >( 120 );
            Unknown121 = parser.ReadColumn< byte >( 121 );
            Unknown122 = parser.ReadColumn< byte >( 122 );
            Unknown123 = parser.ReadColumn< byte >( 123 );
            Unknown124 = parser.ReadColumn< byte >( 124 );
            Unknown125 = parser.ReadColumn< byte >( 125 );
            Unknown126 = parser.ReadColumn< byte >( 126 );
            Unknown127 = parser.ReadColumn< byte >( 127 );
            Unknown128 = parser.ReadColumn< byte >( 128 );
            Unknown129 = parser.ReadColumn< byte >( 129 );
            Unknown130 = parser.ReadColumn< byte >( 130 );
            Unknown131 = parser.ReadColumn< byte >( 131 );
            Unknown132 = parser.ReadColumn< byte >( 132 );
            Unknown133 = parser.ReadColumn< byte >( 133 );
            Unknown134 = parser.ReadColumn< byte >( 134 );
            Unknown135 = parser.ReadColumn< byte >( 135 );
            Unknown136 = parser.ReadColumn< byte >( 136 );
            Unknown137 = parser.ReadColumn< byte >( 137 );
            Unknown138 = parser.ReadColumn< byte >( 138 );
            Unknown139 = parser.ReadColumn< byte >( 139 );
            Unknown140 = parser.ReadColumn< byte >( 140 );
            Unknown141 = parser.ReadColumn< byte >( 141 );
            Unknown142 = parser.ReadColumn< byte >( 142 );
            Unknown143 = parser.ReadColumn< byte >( 143 );
            Unknown144 = parser.ReadColumn< byte >( 144 );
            Unknown145 = parser.ReadColumn< byte >( 145 );
            Unknown146 = parser.ReadColumn< byte >( 146 );
            Unknown147 = parser.ReadColumn< byte >( 147 );
            Unknown148 = parser.ReadColumn< byte >( 148 );
            Unknown149 = parser.ReadColumn< byte >( 149 );
            Unknown150 = parser.ReadColumn< byte >( 150 );
            Unknown151 = parser.ReadColumn< byte >( 151 );
            Unknown152 = parser.ReadColumn< byte >( 152 );
            Unknown153 = parser.ReadColumn< byte >( 153 );
            Unknown154 = parser.ReadColumn< byte >( 154 );
            Unknown155 = parser.ReadColumn< byte >( 155 );
            Unknown156 = parser.ReadColumn< byte >( 156 );
            Unknown157 = parser.ReadColumn< byte >( 157 );
            Unknown158 = parser.ReadColumn< byte >( 158 );
            Unknown159 = parser.ReadColumn< byte >( 159 );
            Unknown160 = parser.ReadColumn< byte >( 160 );
            Unknown161 = parser.ReadColumn< byte >( 161 );
            Unknown162 = parser.ReadColumn< byte >( 162 );
            Unknown163 = parser.ReadColumn< byte >( 163 );
            Unknown164 = parser.ReadColumn< byte >( 164 );
            Unknown165 = parser.ReadColumn< byte >( 165 );
            Unknown166 = parser.ReadColumn< byte >( 166 );
            Unknown167 = parser.ReadColumn< byte >( 167 );
            Unknown168 = parser.ReadColumn< byte >( 168 );
            Unknown169 = parser.ReadColumn< byte >( 169 );
            Unknown170 = parser.ReadColumn< byte >( 170 );
            Unknown171 = parser.ReadColumn< byte >( 171 );
            Unknown172 = parser.ReadColumn< byte >( 172 );
            Unknown173 = parser.ReadColumn< byte >( 173 );
            Unknown174 = parser.ReadColumn< byte >( 174 );
            Unknown175 = parser.ReadColumn< byte >( 175 );
            Unknown176 = parser.ReadColumn< byte >( 176 );
            Unknown177 = parser.ReadColumn< byte >( 177 );
            Unknown178 = parser.ReadColumn< byte >( 178 );
            Unknown179 = parser.ReadColumn< byte >( 179 );
            Unknown180 = parser.ReadColumn< byte >( 180 );
            Unknown181 = parser.ReadColumn< byte >( 181 );
            Unknown182 = parser.ReadColumn< byte >( 182 );
            Unknown183 = parser.ReadColumn< byte >( 183 );
            Unknown184 = parser.ReadColumn< byte >( 184 );
            Unknown185 = parser.ReadColumn< byte >( 185 );
            Unknown186 = parser.ReadColumn< byte >( 186 );
            Unknown187 = parser.ReadColumn< byte >( 187 );
            Unknown188 = parser.ReadColumn< byte >( 188 );
            Unknown189 = parser.ReadColumn< byte >( 189 );
            Unknown190 = parser.ReadColumn< byte >( 190 );
            Unknown191 = parser.ReadColumn< byte >( 191 );
            Unknown192 = parser.ReadColumn< byte >( 192 );
            Unknown193 = parser.ReadColumn< byte >( 193 );
            Unknown194 = parser.ReadColumn< byte >( 194 );
            Unknown195 = parser.ReadColumn< byte >( 195 );
            Unknown196 = parser.ReadColumn< byte >( 196 );
            Unknown197 = parser.ReadColumn< byte >( 197 );
            Unknown198 = parser.ReadColumn< byte >( 198 );
            Unknown199 = parser.ReadColumn< byte >( 199 );
            Unknown200 = parser.ReadColumn< byte >( 200 );
            Unknown201 = parser.ReadColumn< byte >( 201 );
            Unknown202 = parser.ReadColumn< byte >( 202 );
            Unknown203 = parser.ReadColumn< byte >( 203 );
            Unknown204 = parser.ReadColumn< byte >( 204 );
            Unknown205 = parser.ReadColumn< byte >( 205 );
            Unknown206 = parser.ReadColumn< byte >( 206 );
            Unknown207 = parser.ReadColumn< byte >( 207 );
            Unknown208 = parser.ReadColumn< byte >( 208 );
            Unknown209 = parser.ReadColumn< byte >( 209 );
            Unknown210 = parser.ReadColumn< byte >( 210 );
            Unknown211 = parser.ReadColumn< byte >( 211 );
            Unknown212 = parser.ReadColumn< byte >( 212 );
            Unknown213 = parser.ReadColumn< byte >( 213 );
            Unknown214 = parser.ReadColumn< byte >( 214 );
            Unknown215 = parser.ReadColumn< byte >( 215 );
            Unknown216 = parser.ReadColumn< byte >( 216 );
            Unknown217 = parser.ReadColumn< byte >( 217 );
            Unknown218 = parser.ReadColumn< byte >( 218 );
            Unknown219 = parser.ReadColumn< byte >( 219 );
            Unknown220 = parser.ReadColumn< byte >( 220 );
            Unknown221 = parser.ReadColumn< byte >( 221 );
            Unknown222 = parser.ReadColumn< byte >( 222 );
            Unknown223 = parser.ReadColumn< byte >( 223 );
            Unknown224 = parser.ReadColumn< byte >( 224 );
            Unknown225 = parser.ReadColumn< byte >( 225 );
            Unknown226 = parser.ReadColumn< byte >( 226 );
            Unknown227 = parser.ReadColumn< byte >( 227 );
            Unknown228 = parser.ReadColumn< byte >( 228 );
            Unknown229 = parser.ReadColumn< byte >( 229 );
            Unknown230 = parser.ReadColumn< byte >( 230 );
            Unknown231 = parser.ReadColumn< byte >( 231 );
            Unknown232 = parser.ReadColumn< byte >( 232 );
            Unknown233 = parser.ReadColumn< byte >( 233 );
            Unknown234 = parser.ReadColumn< byte >( 234 );
            Unknown235 = parser.ReadColumn< byte >( 235 );
            Unknown236 = parser.ReadColumn< byte >( 236 );
            Unknown237 = parser.ReadColumn< byte >( 237 );
            Unknown238 = parser.ReadColumn< byte >( 238 );
            Unknown239 = parser.ReadColumn< byte >( 239 );
            Unknown240 = parser.ReadColumn< byte >( 240 );
            Unknown241 = parser.ReadColumn< byte >( 241 );
            Unknown242 = parser.ReadColumn< byte >( 242 );
            Unknown243 = parser.ReadColumn< byte >( 243 );
            Unknown244 = parser.ReadColumn< byte >( 244 );
            Unknown245 = parser.ReadColumn< byte >( 245 );
            Unknown246 = parser.ReadColumn< byte >( 246 );
            Unknown247 = parser.ReadColumn< byte >( 247 );
            Unknown248 = parser.ReadColumn< byte >( 248 );
            Unknown249 = parser.ReadColumn< byte >( 249 );
            Unknown250 = parser.ReadColumn< byte >( 250 );
            Unknown251 = parser.ReadColumn< byte >( 251 );
            Unknown252 = parser.ReadColumn< byte >( 252 );
            Unknown253 = parser.ReadColumn< byte >( 253 );
            Unknown254 = parser.ReadColumn< byte >( 254 );
            Unknown255 = parser.ReadColumn< byte >( 255 );
            Unknown256 = parser.ReadColumn< byte >( 256 );
            Unknown257 = parser.ReadColumn< byte >( 257 );
            Unknown258 = parser.ReadColumn< byte >( 258 );
            Unknown259 = parser.ReadColumn< byte >( 259 );
            Unknown260 = parser.ReadColumn< byte >( 260 );
            Unknown261 = parser.ReadColumn< byte >( 261 );
            Unknown262 = parser.ReadColumn< byte >( 262 );
            Unknown263 = parser.ReadColumn< byte >( 263 );
            Unknown264 = parser.ReadColumn< byte >( 264 );
            Unknown265 = parser.ReadColumn< byte >( 265 );
            Unknown266 = parser.ReadColumn< byte >( 266 );
            Unknown267 = parser.ReadColumn< byte >( 267 );
            Unknown268 = parser.ReadColumn< byte >( 268 );
            Unknown269 = parser.ReadColumn< byte >( 269 );
            Unknown270 = parser.ReadColumn< byte >( 270 );
            Unknown271 = parser.ReadColumn< byte >( 271 );
            Unknown272 = parser.ReadColumn< byte >( 272 );
            Unknown273 = parser.ReadColumn< int >( 273 );
            Unknown274 = parser.ReadColumn< int >( 274 );
            Unknown275 = parser.ReadColumn< int >( 275 );
            Unknown276 = parser.ReadColumn< int >( 276 );
            Unknown277 = parser.ReadColumn< int >( 277 );
            Unknown278 = parser.ReadColumn< int >( 278 );
            Unknown279 = parser.ReadColumn< int >( 279 );
            Unknown280 = parser.ReadColumn< int >( 280 );
            Unknown281 = parser.ReadColumn< int >( 281 );
            Unknown282 = parser.ReadColumn< int >( 282 );
            Unknown283 = parser.ReadColumn< int >( 283 );
            Unknown284 = parser.ReadColumn< int >( 284 );
            Unknown285 = parser.ReadColumn< int >( 285 );
            Unknown286 = parser.ReadColumn< int >( 286 );
            Unknown287 = parser.ReadColumn< int >( 287 );
            Unknown288 = parser.ReadColumn< int >( 288 );
            Unknown289 = parser.ReadColumn< int >( 289 );
            Unknown290 = parser.ReadColumn< int >( 290 );
            Unknown291 = parser.ReadColumn< int >( 291 );
            Unknown292 = parser.ReadColumn< int >( 292 );
            Unknown293 = parser.ReadColumn< int >( 293 );
            Unknown294 = parser.ReadColumn< int >( 294 );
            Unknown295 = parser.ReadColumn< int >( 295 );
            Unknown296 = parser.ReadColumn< int >( 296 );
            Unknown297 = parser.ReadColumn< int >( 297 );
            Unknown298 = parser.ReadColumn< int >( 298 );
            Unknown299 = parser.ReadColumn< int >( 299 );
            Unknown300 = parser.ReadColumn< int >( 300 );
            Unknown301 = parser.ReadColumn< int >( 301 );
            Unknown302 = parser.ReadColumn< int >( 302 );
            Unknown303 = parser.ReadColumn< int >( 303 );
            Unknown304 = parser.ReadColumn< int >( 304 );
            Unknown305 = parser.ReadColumn< int >( 305 );
            Unknown306 = parser.ReadColumn< int >( 306 );
            Unknown307 = parser.ReadColumn< int >( 307 );
            Unknown308 = parser.ReadColumn< int >( 308 );
            Unknown309 = parser.ReadColumn< int >( 309 );
            Unknown310 = parser.ReadColumn< int >( 310 );
            Unknown311 = parser.ReadColumn< int >( 311 );
            Unknown312 = parser.ReadColumn< int >( 312 );
            Unknown313 = parser.ReadColumn< int >( 313 );
            Unknown314 = parser.ReadColumn< int >( 314 );
            Unknown315 = parser.ReadColumn< int >( 315 );
            Unknown316 = parser.ReadColumn< int >( 316 );
            Unknown317 = parser.ReadColumn< int >( 317 );
            Unknown318 = parser.ReadColumn< int >( 318 );
            Unknown319 = parser.ReadColumn< int >( 319 );
            Unknown320 = parser.ReadColumn< int >( 320 );
            Unknown321 = parser.ReadColumn< int >( 321 );
            Unknown322 = parser.ReadColumn< int >( 322 );
            Unknown323 = parser.ReadColumn< int >( 323 );
            Unknown324 = parser.ReadColumn< int >( 324 );
            Unknown325 = parser.ReadColumn< int >( 325 );
            Unknown326 = parser.ReadColumn< int >( 326 );
            Unknown327 = parser.ReadColumn< int >( 327 );
            Unknown328 = parser.ReadColumn< int >( 328 );
            Unknown329 = parser.ReadColumn< int >( 329 );
            Unknown330 = parser.ReadColumn< int >( 330 );
            Unknown331 = parser.ReadColumn< int >( 331 );
            Unknown332 = parser.ReadColumn< int >( 332 );
            Unknown333 = parser.ReadColumn< int >( 333 );
            Unknown334 = parser.ReadColumn< int >( 334 );
            Unknown335 = parser.ReadColumn< int >( 335 );
            Unknown336 = parser.ReadColumn< int >( 336 );
            Unknown337 = parser.ReadColumn< int >( 337 );
            Unknown338 = parser.ReadColumn< int >( 338 );
            Unknown339 = parser.ReadColumn< int >( 339 );
            Unknown340 = parser.ReadColumn< int >( 340 );
            Unknown341 = parser.ReadColumn< int >( 341 );
            Unknown342 = parser.ReadColumn< int >( 342 );
            Unknown343 = parser.ReadColumn< int >( 343 );
            Unknown344 = parser.ReadColumn< int >( 344 );
            Unknown345 = parser.ReadColumn< int >( 345 );
            Unknown346 = parser.ReadColumn< int >( 346 );
            Unknown347 = parser.ReadColumn< int >( 347 );
            Unknown348 = parser.ReadColumn< int >( 348 );
            Unknown349 = parser.ReadColumn< int >( 349 );
            Unknown350 = parser.ReadColumn< int >( 350 );
            Unknown351 = parser.ReadColumn< int >( 351 );
            Unknown352 = parser.ReadColumn< int >( 352 );
            Unknown353 = parser.ReadColumn< int >( 353 );
            Unknown354 = parser.ReadColumn< int >( 354 );
            Unknown355 = parser.ReadColumn< int >( 355 );
            Unknown356 = parser.ReadColumn< int >( 356 );
            Unknown357 = parser.ReadColumn< int >( 357 );
            Unknown358 = parser.ReadColumn< int >( 358 );
            Unknown359 = parser.ReadColumn< int >( 359 );
            Unknown360 = parser.ReadColumn< int >( 360 );
            Unknown361 = parser.ReadColumn< int >( 361 );
            Unknown362 = parser.ReadColumn< int >( 362 );
            Unknown363 = parser.ReadColumn< int >( 363 );
            Unknown364 = parser.ReadColumn< int >( 364 );
            Unknown365 = parser.ReadColumn< int >( 365 );
            Unknown366 = parser.ReadColumn< int >( 366 );
            Unknown367 = parser.ReadColumn< int >( 367 );
            Unknown368 = parser.ReadColumn< int >( 368 );
        }
    }
}